// Generated by sprotodump. DO NOT EDIT!

class C2sProtocol extends Sproto.ProtocolBase {
	public static readonly checkAccount: number = 1
	public static readonly QueryList: number = 2
	public static readonly EnterGame: number = 3
	public static readonly CreateActor: number = 4
	public static readonly RandName: number = 5
	public static readonly cs_base_get_game_time: number = 6
	public static readonly UpdateHead: number = 7
	public static readonly cs_sene_gm_command: number = 100
	public static readonly cs_create_new_sub_role: number = 102
	public static readonly cs_get_server_time: number = 114
	public static readonly cs_get_other_actor_info: number = 116
	public static readonly cs_get_actor_module_isactive: number = 119
	public static readonly cs_change_actor_name: number = 122
	public static readonly cs_get_gongnengyugao_reward: number = 123
	public static readonly cs_set_clientvalue: number = 124
	public static readonly cs_baserecord_info: number = 125
	public static readonly cs_set_is_open_payfrist: number = 127
	public static readonly cs_zs_point_req: number = 128
	public static readonly cs_add_zs_point: number = 129
	public static readonly cs_zs_point_clear: number = 130
	public static readonly cs_jingmai_boost: number = 131
	public static readonly cs_jingmai_upgrade: number = 132
	public static readonly cs_jingmai_stage: number = 133
	public static readonly cs_element_set_req: number = 141
	public static readonly cs_client_ready_req: number = 150
	public static readonly cs_send_heart_beat: number = 199
	public static readonly cs_raid_wave_complete: number = 201
	public static readonly cs_raid_pk_boss: number = 202
	public static readonly cs_raid_get_boss_reward: number = 203
	public static readonly cs_raid_exit_raid: number = 204
	public static readonly cs_raid_get_award: number = 205
	public static readonly cs_raid_get_world_award: number = 206
	public static readonly cs_raid_challenget: number = 210
	public static readonly cs_raid_add_count: number = 211
	public static readonly cs_raid_call_boss_play: number = 212
	public static readonly sc_raid_clear_cd: number = 213
	public static readonly cs_raid_artifact: number = 217
	public static readonly cs_raid_artifact_award: number = 218
	public static readonly cs_raid_artifact_info: number = 222
	public static readonly cs_raid_artifact_morra: number = 223
	public static readonly cs_raid_next_chapter_req: number = 226
	public static readonly cs_raid_guardian_req: number = 227
	public static readonly cs_raid_guardian_fight_req: number = 228
	public static readonly cs_raid_guardian_quick_req: number = 229
	public static readonly cs_raid_guardian_tili_req: number = 230
	public static readonly cs_raid_artifact_buy_req: number = 231
	public static readonly cs_offline_apply_req: number = 235
	public static readonly cs_use_skill: number = 301
	public static readonly cs_skill_upgrade: number = 304
	public static readonly cs_skill_upgrade_all: number = 305
	public static readonly cs_skill_break: number = 308
	public static readonly cs_skill_setfight_req: number = 309
	public static readonly cs_get_other_actor_base_info: number = 350
	public static readonly cs_rank_player_info: number = 400
	public static readonly cs_bag_add_grid: number = 401
	public static readonly cs_bag_use_item: number = 402
	public static readonly cs_bag_get_goods_by_store: number = 403
	public static readonly cs_bag_mix_item: number = 407
	public static readonly cs_bag_get_tendraw_by_store: number = 409
	public static readonly cs_bag_compose_item: number = 412
	public static readonly cs_bag_danyao_info: number = 414
	public static readonly cs_bag_danyao_eat: number = 415
	public static readonly cs_bag_danyao_cd: number = 417
	public static readonly cs_bag_get_ticket_by_store: number = 418
	public static readonly cs_equip_wear: number = 501
	public static readonly cs_equip_smelt: number = 502
	public static readonly cs_equip_upgrade: number = 503
	public static readonly cs_equip_mix: number = 504
	public static readonly cs_equip_autosmelt_req: number = 505
	public static readonly cs_equip_resolve: number = 506
	public static readonly cs_exten_id: number = 510
	public static readonly cs_encounter_send_fight_refresh: number = 601
	public static readonly cs_encounter_send_fight_result: number = 602
	public static readonly cs_encounter_inquire_record: number = 604
	public static readonly cs_encounter_send_result: number = 605
	public static readonly cs_encounter_get_boss_award: number = 606
	public static readonly cs_encounter_inquire_prestige: number = 607
	public static readonly cs_encounter_clear_redpoint: number = 608
	public static readonly cs_encounter_open_item: number = 610
	public static readonly cs_encounter_get_item_info: number = 611
	public static readonly cs_encounter_buy_pk_count: number = 612
	public static readonly cs_encounter_send_revenge: number = 613
	public static readonly cs_encounter_get_info: number = 614
	public static readonly cs_encounter_get_news: number = 615
	public static readonly cs_wing_boost: number = 702
	public static readonly cs_wing_upgrade: number = 703
	public static readonly cs_wing_activate: number = 704
	public static readonly cs_wing_equip: number = 711
	public static readonly cs_wing_evolution: number = 712
	public static readonly cs_wing_onekey: number = 713
	public static readonly cs_wing_exten: number = 715
	public static readonly cs_forge_upgrade_grade: number = 802
	public static readonly cs_forge_upgrade_bless: number = 803
	public static readonly cs_forge_back_upgrade_goods: number = 804
	public static readonly cs_forge_bless_ronglu_success: number = 805
	public static readonly cs_forge_bless_boost_req: number = 806
	public static readonly cs_forge_bless_upgrade_req: number = 807
	public static readonly cs_forge_bless_smelt_req: number = 808
	public static readonly cs_forge_onekey: number = 809
	public static readonly cs_mail_get_content: number = 901
	public static readonly cs_mail_get_reward: number = 902
	public static readonly cs_mail_init: number = 903
	public static readonly cs_mail_delet: number = 904
	public static readonly cs_task_get_task: number = 1001
	public static readonly cs_task_get_vitality_awards: number = 1002
	public static readonly cs_task_get_achieve: number = 1003
	public static readonly cs_task_share_open: number = 1004
	public static readonly cs_task_warorder_reward: number = 1005
	public static readonly cs_task_apply_vitality: number = 1010
	public static readonly cs_public_boss_send_panel_info: number = 1101
	public static readonly cs_public_boss_send_boos_list: number = 1102
	public static readonly cs_public_boss_save_remind: number = 1103
	public static readonly cs_public_boss_challenge_record: number = 1104
	public static readonly cs_public_boss_challenge: number = 1105
	public static readonly cs_public_boss_rank: number = 1106
	public static readonly cs_public_boss_send_init_info: number = 1110
	public static readonly cs_public_boss_clear_cd: number = 1114
	public static readonly cs_public_challenge_owner: number = 1115
	public static readonly cs_public_relive_cd: number = 1116
	public static readonly cs_public_boss_save_autofight: number = 1117
	public static readonly cs_public_boss_attack_player: number = 1118
	public static readonly cs_cross_boss_panel_info: number = 1119
	public static readonly cs_cross_boss_challenge: number = 1120
	public static readonly cs_vip_boss_challenge_time: number = 1130
	public static readonly cs_vip_boss_init_panel_info: number = 1133
	public static readonly cs_vip_boss_refresh_remind: number = 1135
	public static readonly cs_vip_boss_remind_panel_info: number = 1137
	public static readonly cs_paidboss_req: number = 1140
	public static readonly cs_paidboss_setting_req: number = 1141
	public static readonly cs_paidboss_fight_req: number = 1142
	public static readonly cs_gem_upgrade_grade: number = 1202
	public static readonly cs_gem_onekey: number = 1203
	public static readonly cs_zs_get_exp: number = 1401
	public static readonly cs_zs_uplevel: number = 1402
	public static readonly cs_essence_upgrade_grade: number = 1502
	public static readonly cs_essence_onekey: number = 1503
	public static readonly cs_shop_buy: number = 1702
	public static readonly cs_shop_refresh: number = 1703
	public static readonly cs_shop_buy_jifen: number = 1705
	public static readonly cs_shop_medal_message: number = 1706
	public static readonly cs_shop_buy_medal: number = 1707
	public static readonly cs_shop_start_refresh: number = 1708
	public static readonly cs_shop_godequip_buy: number = 1709
	public static readonly cs_shop_cross_tianti_glory_buy: number = 1713
	public static readonly cs_shop_cross_tianti_glory_times: number = 1714
	public static readonly cs_rank_req: number = 1901
	public static readonly cs_rank_worship_data_req: number = 1902
	public static readonly cs_rank_worship_once: number = 1903
	public static readonly cs_rank_worship_all_count: number = 1904
	public static readonly sc_vip_get_awards: number = 2001
	public static readonly cs_treasure_hunt: number = 2301
	public static readonly cs_treasure_record: number = 2302
	public static readonly cs_enter_treasure_raid: number = 2303
	public static readonly cs_get_treasure_daily_award: number = 2304
	public static readonly cs_get_treasure_boss_list: number = 2305
	public static readonly cs_petsSearch_hunt: number = 2306
	public static readonly cs_ticket_treasure_hunt: number = 2401
	public static readonly cs_ticket_treasure_record: number = 2402
	public static readonly cs_ticket_treasure_reward: number = 2403
	public static readonly cs_buy_vipshop_item: number = 2450
	public static readonly cs_vipshop_info: number = 2451
	public static readonly cs_challenge_raid_send: number = 2501
	public static readonly cs_challenge_raid_day_reward: number = 2502
	public static readonly cs_challenge_raid_new_reward: number = 2503
	public static readonly cs_activity_send_reward: number = 2602
	public static readonly cs_activity_send_dabiao_info: number = 2603
	public static readonly cs_activity_send_level_info: number = 2604
	public static readonly cs_yb_turntable_info: number = 2615
	public static readonly cs_yb_roll_start: number = 2617
	public static readonly cs_rebate_activity_info: number = 2650
	public static readonly cs_rebate_activity_buy: number = 2651
	public static readonly cs_rebate_activity_gain_other_awards: number = 2652
	public static readonly cs_one_recharge_activity_state: number = 2653
	public static readonly cs_one_recharge_activity_gain: number = 2654
	public static readonly cs_mond_Sign_send_reward: number = 2655
	public static readonly cs_luckywheel_hunt: number = 2656
	public static readonly cs_luckywheel_record: number = 2657
	public static readonly cs_luckywheel_rank: number = 2658
	public static readonly cs_small_routine_gain: number = 2659
	public static readonly cs_add_small_routine_state: number = 2660
	public static readonly cs_activity_buyGoods: number = 2664
	public static readonly cs_activity_warorder_reward: number = 2665
	public static readonly cs_activity_warorder_exreward: number = 2666
	public static readonly cs_activity_warorder_buylv: number = 2667
	public static readonly cs_activity_warorder_buyscale: number = 2668
	public static readonly cs_artifact_uplevel: number = 2702
	public static readonly cs_artifact_stone_req: number = 2704
	public static readonly cs_recharge_get_awards: number = 2801
	public static readonly cs_recharge_test: number = 2802
	public static readonly cs_recharge_test_month: number = 2803
	public static readonly cs_recharge_gift_reward: number = 2804
	public static readonly cs_recharge_month_reward: number = 2805
	public static readonly cs_recharge_test_invest: number = 2806
	public static readonly cs_buy_wanba_item: number = 2808
	public static readonly cs_buy_yyb_item: number = 2809
	public static readonly cs_buy_xiaoyouxi_item: number = 2810
	public static readonly cs_chat_send_info: number = 3101
	public static readonly cs_zhuzai_shengjie: number = 3203
	public static readonly cs_zhuzai_grow: number = 3204
	public static readonly cs_zhuzai_fenjie: number = 3205
	public static readonly cs_zs_boss_list: number = 3301
	public static readonly cs_zs_boss_challenge: number = 3303
	public static readonly cs_zs_boss_rank: number = 3304
	public static readonly cs_zs_boss_join_lottery: number = 3305
	public static readonly cs_zs_boss_buy_cd: number = 3306
	public static readonly cs_world_boss_list: number = 3307
	public static readonly cs_world_boss_challenge: number = 3308
	public static readonly cs_world_boss_buy_cd: number = 3309
	public static readonly cs_world_boss_join_lottery: number = 3310
	public static readonly cs_ladder_get_some_one: number = 3502
	public static readonly cs_ladder_start_play: number = 3503
	public static readonly cs_ladder_get_week_reward: number = 3504
	public static readonly cs_ladder_get_rank_info: number = 3505
	public static readonly cs_ladder_buy_count: number = 3506
	public static readonly cs_ladder_get_record: number = 3507
	public static readonly sc_miji_learn: number = 3602
	public static readonly sc_miji_change: number = 3603
	public static readonly cs_miji_fuben: number = 3604
	public static readonly cs_miji_fuben_panel_info: number = 3605
	public static readonly cs_miji_fuben_quick: number = 3606
	public static readonly cs_miji_fuben_reward: number = 3607
	public static readonly cs_miji_reward_data: number = 3608
	public static readonly cs_money_tree_play: number = 3702
	public static readonly cs_money_tree_reward: number = 3703
	public static readonly cs_money_recharge_get: number = 3704
	public static readonly cs_guild_getinfo: number = 3801
	public static readonly cs_guild_getmembers: number = 3802
	public static readonly cs_guild_getlist: number = 3803
	public static readonly cs_guild_create: number = 3804
	public static readonly cs_guild_quit: number = 3805
	public static readonly cs_guild_join: number = 3806
	public static readonly cs_guild_getapply: number = 3807
	public static readonly cs_guild_setapply: number = 3808
	public static readonly cs_guild_change_office: number = 3809
	public static readonly cs_guild_demise: number = 3810
	public static readonly cs_guild_kick: number = 3811
	public static readonly cs_guild_contribute: number = 3813
	public static readonly cs_guild_change_notice: number = 3814
	public static readonly cs_guild_getskillinfo: number = 3815
	public static readonly cs_guild_learnskill: number = 3816
	public static readonly cs_guild_upbuilding: number = 3817
	public static readonly cs_guild_temperskill: number = 3818
	public static readonly cs_guild_gettaskaward: number = 3821
	public static readonly cs_guild_gethistory: number = 3822
	public static readonly cs_guild_getconcount: number = 3824
	public static readonly cs_guild_getplayerinfo: number = 3825
	public static readonly cs_guild_sendchat: number = 3826
	public static readonly cs_guild_getallchat: number = 3827
	public static readonly cs_guild_setautoadd: number = 3828
	public static readonly cs_title_req: number = 3901
	public static readonly cs_title_set: number = 3904
	public static readonly cs_find_assets_init: number = 4001
	public static readonly cs_find_assets_get: number = 4002
	public static readonly cs_guildwar_send_redpacket: number = 4102
	public static readonly cs_guildwar_get_redpacket: number = 4103
	public static readonly sc_guildwar_get_guild_scores: number = 4108
	public static readonly sc_guildwar_get_actor_scores: number = 4109
	public static readonly cs_guildwar_get_dayaward: number = 4113
	public static readonly cs_guildwar_disp_award: number = 4120
	public static readonly cs_guildwar_get_winnerinfo: number = 4121
	public static readonly cs_guildwar_get_my_guild_rank_info: number = 4122
	public static readonly cs_guildwar_get_firstwinner_award: number = 4123
	public static readonly cs_guildwar_get_winleader: number = 4124
	public static readonly cs_guildwar_get_kffz_info: number = 4125
	public static readonly cs_guildwar_get_kfwin_records: number = 4126
	public static readonly cs_get_cross_tianti_list: number = 4200
	public static readonly cs_cross_start_combat: number = 4201
	public static readonly cs_cross_get_self_info: number = 4202
	public static readonly cs_cross_get_combat_recode: number = 4204
	public static readonly cs_cross_get_tianti_rank_info: number = 4205
	public static readonly cs_cross_get_tianti_history_rank: number = 4206
	public static readonly cs_cross_gain_tianti_history_award: number = 4207
	public static readonly cs_cross_buy_combat_num: number = 4208
	public static readonly cs_guildshop_getinfo: number = 4301
	public static readonly cs_guildshop_getrecord: number = 4302
	public static readonly cs_guildshop_open: number = 4303
	public static readonly cs_gold_guaji_start_combat: number = 4401
	public static readonly cs_gold_guaji_info: number = 4402
	public static readonly cs_gold_guaji_obtain_items_info: number = 4403
	public static readonly cs_gold_guaji_combat_boss: number = 4407
	public static readonly cs_gold_guaji_start_relive: number = 4409
	public static readonly cs_dress_get_info: number = 4501
	public static readonly cs_dress_activate: number = 4502
	public static readonly cs_dress_dress: number = 4503
	public static readonly cs_dress_undress: number = 4504
	public static readonly cs_dress_upgrade: number = 4506
	public static readonly cs_dress_continue: number = 4507
	public static readonly cs_mine_report_mine_info: number = 4901
	public static readonly cs_mine_mapdata: number = 4904
	public static readonly cs_mine_rob: number = 4907
	public static readonly cs_mine_revenge: number = 4908
	public static readonly cs_mine_steal: number = 4909
	public static readonly cs_enter_dragon: number = 5001
	public static readonly cs_Challenge_actor: number = 5002
	public static readonly cs_Challenge_boss: number = 5003
	public static readonly cs_sore_info: number = 5004
	public static readonly cs_dragon_info: number = 5005
	public static readonly cs_revive_actor: number = 5006
	public static readonly cs_receive_sorce_reward: number = 5007
	public static readonly cs_prestige_uplevel: number = 5101
	public static readonly cs_prestige_req_topthree: number = 5102
	public static readonly cs_longzhuang_boost: number = 5302
	public static readonly cs_longzhuang_upgrade: number = 5303
	public static readonly cs_longzhuang_onekey: number = 5304
	public static readonly cs_fuwen_equipup: number = 5401
	public static readonly cs_fuwen_open: number = 5402
	public static readonly cs_expjade_use: number = 5502
	public static readonly cs_legend_dress: number = 5601
	public static readonly cs_redeemcode_use: number = 5701
	public static readonly cs_ring_uplevel: number = 5702
	public static readonly cs_ring_active: number = 5706
	public static readonly cs_ring_soul_evil_change: number = 5707
	public static readonly cs_wash_soul_evil_type: number = 5708
	public static readonly cs_ringboss_init: number = 5711
	public static readonly sc_ringboss_enter_req: number = 5712
	public static readonly sc_ringboss_refresh_req: number = 5713
	public static readonly cs_wanba_redeemcode_use: number = 5715
	public static readonly cs_wanba_share_use: number = 5718
	public static readonly cs_channel_share_use: number = 5719
	public static readonly cs_get_qzonewanba_gift: number = 5720
	public static readonly cs_get_qzonewanba_vipgift: number = 5721
	public static readonly cs_get_qzonewanba_vipprivilege: number = 5722
	public static readonly cs_get_qzonewanba_vipprivilege_stat: number = 5723
	public static readonly cs_update_qzonewanba_token: number = 5724
	public static readonly cs_eggbroken_hunt: number = 5801
	public static readonly cs_eggbroken_record: number = 5802
	public static readonly cs_eggbroken_hitting: number = 5805
	public static readonly cs_holygun_init: number = 6000
	public static readonly cs_holygun_upstar: number = 6001
	public static readonly cs_holygun_upscala: number = 6002
	public static readonly cs_holygun_upskill: number = 6003
	public static readonly cs_holygun_eatdanyao: number = 6004
	public static readonly cs_holygun_achievement: number = 6005
	public static readonly cs_holygun_reward: number = 6006
	public static readonly cs_operate_share: number = 6702
	public static readonly cs_share_event: number = 6703
	public static readonly cs_share_Help: number = 6705
	public static readonly cs_guild_boss_call: number = 7901
	public static readonly cs_guild_boss_fight: number = 7902
	public static readonly cs_guild_boss_rank: number = 7903
	public static readonly cs_gdwar_enter_cross: number = 8000
	public static readonly cs_gdwar_enter_city: number = 8001
	public static readonly cs_gdwar_leave: number = 8002
	public static readonly cs_gdwar_update: number = 8005
	public static readonly cs_gdwar_attack_monster: number = 8006
	public static readonly cs_gdwar_attack_player: number = 8007
	public static readonly cs_gdwar_integral_reward: number = 8008
	public static readonly cs_gdwar_guild_rank: number = 8009
	public static readonly cs_gdwar_actor_rank: number = 8010
	public static readonly cs_gdwar_guild_member: number = 8011
	public static readonly cs_gdwar_guild_get_group: number = 8012
	public static readonly cs_gdwar_lottery_start: number = 8101
	public static readonly cs_gdwar_click_flag: number = 8401
	public static readonly cs_guild_activity_info: number = 9001
	public static readonly cs_guild_robber_info: number = 9011
	public static readonly cs_guild_robber_attack: number = 9012
	public static readonly cs_guild_raid_info: number = 9021
	public static readonly cs_guild_raid_sweep: number = 9022
	public static readonly cs_guild_raid_boost: number = 9023
	public static readonly cs_guild_raid_reward: number = 9024
	public static readonly cs_guild_raid_attack: number = 9025
	public static readonly cs_guild_raid_daily: number = 9026
	public static readonly cs_get_biaoche_list: number = 9600
	public static readonly cs_rob_biaoche: number = 9601
	public static readonly cs_uplevel_biaoche: number = 9602
	public static readonly cs_start_biaoche: number = 9603
	public static readonly cs_rob_biaoche_award: number = 9604
	public static readonly cs_biaoche_get_revenge_list: number = 9605
	public static readonly cs_biaoche_revenge: number = 9606
	public static readonly cs_enter_tryroad_raid: number = 21003
	public static readonly cs_get_caiquan_result: number = 21004
	public static readonly cs_get_tryroad_award: number = 21005
	public static readonly cs_get_tryroad_rank: number = 21006
	public static readonly cs_zhuanzhi_active: number = 22001
	public static readonly cs_zhuanzhi_tasklist_req: number = 22002
	public static readonly cs_zhuanzhi_enter_raid: number = 22004
	public static readonly cs_equip_star_upgrade: number = 22005
	public static readonly cs_equip_lvl_upgrade: number = 22006
	public static readonly cs_zhuanzhi_donate: number = 22007
	public static readonly cs_equip_zhuanzhi_skill: number = 22010
	public static readonly cs_zhuanzhi_jingmai_boost: number = 22011
	public static readonly cs_zhuanzhi_jingmai_upgrade: number = 22012
	public static readonly cs_zhuanzhi_talent_upgrade: number = 22022
	public static readonly cs_faq_req: number = 22100
	public static readonly cs_luckypackage_testbuy_req: number = 22111
	public static readonly cs_online_req: number = 22121
	public static readonly cs_online_reward_req: number = 22122
	public static readonly cs_funopen_close_req: number = 22131
	public static readonly cs_monopoly_req: number = 22200
	public static readonly cs_monopoly_dice_req: number = 22202
	public static readonly cs_monopoly_cheat_req: number = 22203
	public static readonly cs_monopoly_buy_req: number = 22204
	public static readonly cs_monopoly_use_req: number = 22205
	public static readonly cs_monopoly_exchange_req: number = 22207
	public static readonly cs_monopoly_store_req: number = 22208
	public static readonly cs_monopoly_rank_req: number = 22209
	public static readonly cs_monopoly_fire_req: number = 22211
	public static readonly cs_monopoly_raid_open: number = 22214
	public static readonly cs_monopoly_tili_req: number = 22215
	public static readonly cs_fieldexp_buff_req: number = 22500
	public static readonly cs_fieldexp_buff_apply_req: number = 22501
	public static readonly cs_fieldexp_buff_finish_req: number = 22502
	public static readonly cs_shapeshift_send_join: number = 25001
	public static readonly cs_shapeshift_send_upgrade: number = 25002
	public static readonly cs_shapeshift_send_info: number = 25003
	public static readonly cs_tendraw_send_draw: number = 25007
	public static readonly cs_tendraw_send_info: number = 25011
	public static readonly cs_shapeshift_send_comcard: number = 25013
	public static readonly cs_shiliansha_send_enter: number = 26001
	public static readonly cs_shiliansha_send_buy_buff: number = 26002
	public static readonly cs_shiliansha_send_buff: number = 26005
	public static readonly cs_shiliansha_send_info: number = 26006
	public static readonly cs_shiliansha_send_continue: number = 26007
	public static readonly cs_neigong_upstar: number = 27001
	public static readonly cs_neigong_uppro: number = 27002
	public static readonly cs_neigong_info: number = 27003
	public static readonly cs_pet_init_req: number = 30000
	public static readonly cs_pet_uplevel_req: number = 30001
	public static readonly cs_pet_upstar_req: number = 30002
	public static readonly cs_pet_activate_req: number = 30003
	public static readonly cs_pet_rename_req: number = 30004
	public static readonly cs_pet_setfight_req: number = 30005
	public static readonly cs_pet_skillup_req: number = 30006
	public static readonly cs_pet_wash_req: number = 30007
	public static readonly cs_pet_attach_init_req: number = 30008
	public static readonly cs_pet_attach_unlock_req: number = 30009
	public static readonly cs_pet_attach_req: number = 30010
	public static readonly cs_pet_washlock_req: number = 30011
	public static readonly cs_pet_washrep_req: number = 30012
	public static readonly cs_pet_smelt_req: number = 30014
	public static readonly cs_pet_compose_req: number = 30015
	public static readonly cs_pet_wake_req: number = 30016
	public static readonly cs_pet_pack_req: number = 30017
	public static readonly cs_ride_init_req: number = 30100
	public static readonly cs_ride_uplevel_req: number = 30101
	public static readonly cs_ride_upstar_req: number = 30102
	public static readonly cs_ride_skillup_req: number = 30105
	public static readonly cs_ride_equip_uplevel_req: number = 30106
	public static readonly cs_ride_equip_upstar_req: number = 30107
	public static readonly cs_ride_equipchange_req: number = 30108
	public static readonly cs_ride_equipoff_req: number = 30109
	public static readonly cs_ride_eat_req: number = 30110
	public static readonly cs_ride_getaward_req: number = 30111
	public static readonly cs_ride_change_req: number = 30112
	public static readonly cs_tower_init_req: number = 30300
	public static readonly cs_tower_award_req: number = 30301
	public static readonly cs_tower_enter_req: number = 30303
	public static readonly cs_tower_sweep_req: number = 30304
	public static readonly cs_tower_floor_req: number = 30305
	public static readonly cs_tatoo_init_req: number = 30401
	public static readonly cs_tatoo_equipon_req: number = 30402
	public static readonly cs_tatoo_equipoff_req: number = 30403
	public static readonly cs_tatoo_strength_req: number = 30404
	public static readonly cs_team_req: number = 30501
	public static readonly cs_team_info_req: number = 30502
	public static readonly cs_team_join_req: number = 30503
	public static readonly cs_team_quit_req: number = 30504
	public static readonly cs_team_kick_req: number = 30505
	public static readonly cs_team_fight_req: number = 30506
	public static readonly cs_one_gift_rewards: number = 30520
	public static readonly cs_one_gift_buy_test: number = 30521
	public constructor() {
		super()
		this.Protocol.SetProtocol(C2sProtocol.CreateActor);
		this.Protocol.SetRequest(C2sProtocol.CreateActor, Sproto.CreateActor_request);
		this.Protocol.SetResponse(C2sProtocol.CreateActor, Sproto.CreateActor_response);

		this.Protocol.SetProtocol(C2sProtocol.EnterGame);
		this.Protocol.SetRequest(C2sProtocol.EnterGame, Sproto.EnterGame_request);
		this.Protocol.SetResponse(C2sProtocol.EnterGame, Sproto.EnterGame_response);

		this.Protocol.SetProtocol(C2sProtocol.QueryList);
		this.Protocol.SetRequest(C2sProtocol.QueryList, Sproto.QueryList_request);
		this.Protocol.SetResponse(C2sProtocol.QueryList, Sproto.QueryList_response);

		this.Protocol.SetProtocol(C2sProtocol.RandName);
		this.Protocol.SetRequest(C2sProtocol.RandName, Sproto.RandName_request);
		this.Protocol.SetResponse(C2sProtocol.RandName, Sproto.RandName_response);

		this.Protocol.SetProtocol(C2sProtocol.UpdateHead);
		this.Protocol.SetRequest(C2sProtocol.UpdateHead, Sproto.UpdateHead_request);

		this.Protocol.SetProtocol(C2sProtocol.checkAccount);
		this.Protocol.SetRequest(C2sProtocol.checkAccount, Sproto.checkAccount_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_Challenge_actor);
		this.Protocol.SetRequest(C2sProtocol.cs_Challenge_actor, Sproto.cs_Challenge_actor_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_Challenge_boss);
		this.Protocol.SetRequest(C2sProtocol.cs_Challenge_boss, Sproto.cs_Challenge_boss_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_activity_buyGoods);
		this.Protocol.SetRequest(C2sProtocol.cs_activity_buyGoods, Sproto.cs_activity_buyGoods_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_activity_send_dabiao_info);
		this.Protocol.SetRequest(C2sProtocol.cs_activity_send_dabiao_info, Sproto.cs_activity_send_dabiao_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_activity_send_level_info);
		this.Protocol.SetRequest(C2sProtocol.cs_activity_send_level_info, Sproto.cs_activity_send_level_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_activity_send_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_activity_send_reward, Sproto.cs_activity_send_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_activity_warorder_buylv);
		this.Protocol.SetRequest(C2sProtocol.cs_activity_warorder_buylv, Sproto.cs_activity_warorder_buylv_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_activity_warorder_buyscale);
		this.Protocol.SetRequest(C2sProtocol.cs_activity_warorder_buyscale, Sproto.cs_activity_warorder_buyscale_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_activity_warorder_exreward);
		this.Protocol.SetRequest(C2sProtocol.cs_activity_warorder_exreward, Sproto.cs_activity_warorder_exreward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_activity_warorder_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_activity_warorder_reward, Sproto.cs_activity_warorder_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_add_small_routine_state);
		this.Protocol.SetRequest(C2sProtocol.cs_add_small_routine_state, Sproto.cs_add_small_routine_state_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_add_zs_point);
		this.Protocol.SetRequest(C2sProtocol.cs_add_zs_point, Sproto.cs_add_zs_point_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_artifact_stone_req);
		this.Protocol.SetRequest(C2sProtocol.cs_artifact_stone_req, Sproto.cs_artifact_stone_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_artifact_uplevel);
		this.Protocol.SetRequest(C2sProtocol.cs_artifact_uplevel, Sproto.cs_artifact_uplevel_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_add_grid);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_add_grid, Sproto.cs_bag_add_grid_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_compose_item);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_compose_item, Sproto.cs_bag_compose_item_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_danyao_cd);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_danyao_cd, Sproto.cs_bag_danyao_cd_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_danyao_eat);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_danyao_eat, Sproto.cs_bag_danyao_eat_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_danyao_info);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_danyao_info, Sproto.cs_bag_danyao_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_get_goods_by_store);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_get_goods_by_store, Sproto.cs_bag_get_goods_by_store_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_get_tendraw_by_store);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_get_tendraw_by_store, Sproto.cs_bag_get_tendraw_by_store_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_get_ticket_by_store);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_get_ticket_by_store, Sproto.cs_bag_get_ticket_by_store_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_mix_item);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_mix_item, Sproto.cs_bag_mix_item_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_bag_use_item);
		this.Protocol.SetRequest(C2sProtocol.cs_bag_use_item, Sproto.cs_bag_use_item_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_base_get_game_time);

		this.Protocol.SetProtocol(C2sProtocol.cs_baserecord_info);
		this.Protocol.SetRequest(C2sProtocol.cs_baserecord_info, Sproto.cs_baserecord_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_biaoche_get_revenge_list);
		this.Protocol.SetRequest(C2sProtocol.cs_biaoche_get_revenge_list, Sproto.cs_biaoche_get_revenge_list_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_biaoche_revenge);
		this.Protocol.SetRequest(C2sProtocol.cs_biaoche_revenge, Sproto.cs_biaoche_revenge_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_buy_vipshop_item);
		this.Protocol.SetRequest(C2sProtocol.cs_buy_vipshop_item, Sproto.cs_buy_vipshop_item_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_buy_wanba_item);
		this.Protocol.SetRequest(C2sProtocol.cs_buy_wanba_item, Sproto.cs_buy_wanba_item_request);
		this.Protocol.SetResponse(C2sProtocol.cs_buy_wanba_item, Sproto.cs_buy_wanba_item_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_buy_xiaoyouxi_item);
		this.Protocol.SetRequest(C2sProtocol.cs_buy_xiaoyouxi_item, Sproto.cs_buy_xiaoyouxi_item_request);
		this.Protocol.SetResponse(C2sProtocol.cs_buy_xiaoyouxi_item, Sproto.cs_buy_xiaoyouxi_item_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_buy_yyb_item);
		this.Protocol.SetRequest(C2sProtocol.cs_buy_yyb_item, Sproto.cs_buy_yyb_item_request);
		this.Protocol.SetResponse(C2sProtocol.cs_buy_yyb_item, Sproto.cs_buy_yyb_item_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_challenge_raid_day_reward);

		this.Protocol.SetProtocol(C2sProtocol.cs_challenge_raid_new_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_challenge_raid_new_reward, Sproto.cs_challenge_raid_new_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_challenge_raid_send);

		this.Protocol.SetProtocol(C2sProtocol.cs_change_actor_name);
		this.Protocol.SetRequest(C2sProtocol.cs_change_actor_name, Sproto.cs_change_actor_name_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_channel_share_use);
		this.Protocol.SetRequest(C2sProtocol.cs_channel_share_use, Sproto.cs_channel_share_use_request);
		this.Protocol.SetResponse(C2sProtocol.cs_channel_share_use, Sproto.cs_channel_share_use_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_chat_send_info);
		this.Protocol.SetRequest(C2sProtocol.cs_chat_send_info, Sproto.cs_chat_send_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_client_ready_req);
		this.Protocol.SetRequest(C2sProtocol.cs_client_ready_req, Sproto.cs_client_ready_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_create_new_sub_role);
		this.Protocol.SetRequest(C2sProtocol.cs_create_new_sub_role, Sproto.cs_create_new_sub_role_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_boss_challenge);
		this.Protocol.SetRequest(C2sProtocol.cs_cross_boss_challenge, Sproto.cs_cross_boss_challenge_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_boss_panel_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_buy_combat_num);
		this.Protocol.SetRequest(C2sProtocol.cs_cross_buy_combat_num, Sproto.cs_cross_buy_combat_num_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_gain_tianti_history_award);
		this.Protocol.SetRequest(C2sProtocol.cs_cross_gain_tianti_history_award, Sproto.cs_cross_gain_tianti_history_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_get_combat_recode);
		this.Protocol.SetRequest(C2sProtocol.cs_cross_get_combat_recode, Sproto.cs_cross_get_combat_recode_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_get_self_info);
		this.Protocol.SetRequest(C2sProtocol.cs_cross_get_self_info, Sproto.cs_cross_get_self_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_get_tianti_history_rank);
		this.Protocol.SetRequest(C2sProtocol.cs_cross_get_tianti_history_rank, Sproto.cs_cross_get_tianti_history_rank_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_get_tianti_rank_info);
		this.Protocol.SetRequest(C2sProtocol.cs_cross_get_tianti_rank_info, Sproto.cs_cross_get_tianti_rank_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_cross_start_combat);
		this.Protocol.SetRequest(C2sProtocol.cs_cross_start_combat, Sproto.cs_cross_start_combat_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_dragon_info);
		this.Protocol.SetRequest(C2sProtocol.cs_dragon_info, Sproto.cs_dragon_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_dress_activate);
		this.Protocol.SetRequest(C2sProtocol.cs_dress_activate, Sproto.cs_dress_activate_request);
		this.Protocol.SetResponse(C2sProtocol.cs_dress_activate, Sproto.cs_dress_activate_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_dress_continue);
		this.Protocol.SetRequest(C2sProtocol.cs_dress_continue, Sproto.cs_dress_continue_request);
		this.Protocol.SetResponse(C2sProtocol.cs_dress_continue, Sproto.cs_dress_continue_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_dress_dress);
		this.Protocol.SetRequest(C2sProtocol.cs_dress_dress, Sproto.cs_dress_dress_request);
		this.Protocol.SetResponse(C2sProtocol.cs_dress_dress, Sproto.cs_dress_dress_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_dress_get_info);
		this.Protocol.SetResponse(C2sProtocol.cs_dress_get_info, Sproto.cs_dress_get_info_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_dress_undress);
		this.Protocol.SetRequest(C2sProtocol.cs_dress_undress, Sproto.cs_dress_undress_request);
		this.Protocol.SetResponse(C2sProtocol.cs_dress_undress, Sproto.cs_dress_undress_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_dress_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_dress_upgrade, Sproto.cs_dress_upgrade_request);
		this.Protocol.SetResponse(C2sProtocol.cs_dress_upgrade, Sproto.cs_dress_upgrade_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_eggbroken_hitting);
		this.Protocol.SetRequest(C2sProtocol.cs_eggbroken_hitting, Sproto.cs_eggbroken_hitting_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_eggbroken_hunt);
		this.Protocol.SetRequest(C2sProtocol.cs_eggbroken_hunt, Sproto.cs_eggbroken_hunt_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_eggbroken_record);
		this.Protocol.SetRequest(C2sProtocol.cs_eggbroken_record, Sproto.cs_eggbroken_record_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_element_set_req);
		this.Protocol.SetRequest(C2sProtocol.cs_element_set_req, Sproto.cs_element_set_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_buy_pk_count);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_clear_redpoint);
		this.Protocol.SetRequest(C2sProtocol.cs_encounter_clear_redpoint, Sproto.cs_encounter_clear_redpoint_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_get_boss_award);
		this.Protocol.SetRequest(C2sProtocol.cs_encounter_get_boss_award, Sproto.cs_encounter_get_boss_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_get_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_get_item_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_get_news);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_inquire_prestige);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_inquire_record);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_open_item);
		this.Protocol.SetRequest(C2sProtocol.cs_encounter_open_item, Sproto.cs_encounter_open_item_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_send_fight_refresh);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_send_fight_result);
		this.Protocol.SetRequest(C2sProtocol.cs_encounter_send_fight_result, Sproto.cs_encounter_send_fight_result_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_send_result);
		this.Protocol.SetRequest(C2sProtocol.cs_encounter_send_result, Sproto.cs_encounter_send_result_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_encounter_send_revenge);
		this.Protocol.SetRequest(C2sProtocol.cs_encounter_send_revenge, Sproto.cs_encounter_send_revenge_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_enter_dragon);
		this.Protocol.SetRequest(C2sProtocol.cs_enter_dragon, Sproto.cs_enter_dragon_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_enter_treasure_raid);
		this.Protocol.SetRequest(C2sProtocol.cs_enter_treasure_raid, Sproto.cs_enter_treasure_raid_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_enter_tryroad_raid);
		this.Protocol.SetRequest(C2sProtocol.cs_enter_tryroad_raid, Sproto.cs_enter_tryroad_raid_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_autosmelt_req);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_autosmelt_req, Sproto.cs_equip_autosmelt_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_lvl_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_lvl_upgrade, Sproto.cs_equip_lvl_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_mix);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_mix, Sproto.cs_equip_mix_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_resolve);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_resolve, Sproto.cs_equip_resolve_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_smelt);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_smelt, Sproto.cs_equip_smelt_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_star_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_star_upgrade, Sproto.cs_equip_star_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_upgrade, Sproto.cs_equip_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_wear);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_wear, Sproto.cs_equip_wear_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_equip_zhuanzhi_skill);
		this.Protocol.SetRequest(C2sProtocol.cs_equip_zhuanzhi_skill, Sproto.cs_equip_zhuanzhi_skill_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_essence_onekey);
		this.Protocol.SetRequest(C2sProtocol.cs_essence_onekey, Sproto.cs_essence_onekey_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_essence_upgrade_grade);
		this.Protocol.SetRequest(C2sProtocol.cs_essence_upgrade_grade, Sproto.cs_essence_upgrade_grade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_expjade_use);
		this.Protocol.SetRequest(C2sProtocol.cs_expjade_use, Sproto.cs_expjade_use_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_exten_id);
		this.Protocol.SetRequest(C2sProtocol.cs_exten_id, Sproto.cs_exten_id_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_faq_req);
		this.Protocol.SetRequest(C2sProtocol.cs_faq_req, Sproto.cs_faq_req_request);
		this.Protocol.SetResponse(C2sProtocol.cs_faq_req, Sproto.cs_faq_req_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_fieldexp_buff_apply_req);
		this.Protocol.SetRequest(C2sProtocol.cs_fieldexp_buff_apply_req, Sproto.cs_fieldexp_buff_apply_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_fieldexp_buff_finish_req);
		this.Protocol.SetRequest(C2sProtocol.cs_fieldexp_buff_finish_req, Sproto.cs_fieldexp_buff_finish_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_fieldexp_buff_req);
		this.Protocol.SetRequest(C2sProtocol.cs_fieldexp_buff_req, Sproto.cs_fieldexp_buff_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_find_assets_get);
		this.Protocol.SetRequest(C2sProtocol.cs_find_assets_get, Sproto.cs_find_assets_get_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_find_assets_init);

		this.Protocol.SetProtocol(C2sProtocol.cs_forge_back_upgrade_goods);
		this.Protocol.SetRequest(C2sProtocol.cs_forge_back_upgrade_goods, Sproto.cs_forge_back_upgrade_goods_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_forge_bless_boost_req);
		this.Protocol.SetRequest(C2sProtocol.cs_forge_bless_boost_req, Sproto.cs_forge_bless_boost_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_forge_bless_ronglu_success);
		this.Protocol.SetRequest(C2sProtocol.cs_forge_bless_ronglu_success, Sproto.cs_forge_bless_ronglu_success_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_forge_bless_smelt_req);
		this.Protocol.SetRequest(C2sProtocol.cs_forge_bless_smelt_req, Sproto.cs_forge_bless_smelt_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_forge_bless_upgrade_req);
		this.Protocol.SetRequest(C2sProtocol.cs_forge_bless_upgrade_req, Sproto.cs_forge_bless_upgrade_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_forge_onekey);
		this.Protocol.SetRequest(C2sProtocol.cs_forge_onekey, Sproto.cs_forge_onekey_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_forge_upgrade_bless);
		this.Protocol.SetRequest(C2sProtocol.cs_forge_upgrade_bless, Sproto.cs_forge_upgrade_bless_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_forge_upgrade_grade);
		this.Protocol.SetRequest(C2sProtocol.cs_forge_upgrade_grade, Sproto.cs_forge_upgrade_grade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_funopen_close_req);
		this.Protocol.SetRequest(C2sProtocol.cs_funopen_close_req, Sproto.cs_funopen_close_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_fuwen_equipup);
		this.Protocol.SetRequest(C2sProtocol.cs_fuwen_equipup, Sproto.cs_fuwen_equipup_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_fuwen_open);
		this.Protocol.SetRequest(C2sProtocol.cs_fuwen_open, Sproto.cs_fuwen_open_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_actor_rank);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_attack_monster);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_attack_player);
		this.Protocol.SetRequest(C2sProtocol.cs_gdwar_attack_player, Sproto.cs_gdwar_attack_player_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_click_flag);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_enter_city);
		this.Protocol.SetRequest(C2sProtocol.cs_gdwar_enter_city, Sproto.cs_gdwar_enter_city_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_enter_cross);
		this.Protocol.SetRequest(C2sProtocol.cs_gdwar_enter_cross, Sproto.cs_gdwar_enter_cross_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_guild_get_group);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_guild_member);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_guild_rank);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_integral_reward);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_leave);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_lottery_start);

		this.Protocol.SetProtocol(C2sProtocol.cs_gdwar_update);

		this.Protocol.SetProtocol(C2sProtocol.cs_gem_onekey);
		this.Protocol.SetRequest(C2sProtocol.cs_gem_onekey, Sproto.cs_gem_onekey_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gem_upgrade_grade);
		this.Protocol.SetRequest(C2sProtocol.cs_gem_upgrade_grade, Sproto.cs_gem_upgrade_grade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_actor_module_isactive);
		this.Protocol.SetRequest(C2sProtocol.cs_get_actor_module_isactive, Sproto.cs_get_actor_module_isactive_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_biaoche_list);
		this.Protocol.SetRequest(C2sProtocol.cs_get_biaoche_list, Sproto.cs_get_biaoche_list_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_caiquan_result);
		this.Protocol.SetRequest(C2sProtocol.cs_get_caiquan_result, Sproto.cs_get_caiquan_result_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_cross_tianti_list);
		this.Protocol.SetRequest(C2sProtocol.cs_get_cross_tianti_list, Sproto.cs_get_cross_tianti_list_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_gongnengyugao_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_get_gongnengyugao_reward, Sproto.cs_get_gongnengyugao_reward_request);
		this.Protocol.SetResponse(C2sProtocol.cs_get_gongnengyugao_reward, Sproto.cs_get_gongnengyugao_reward_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_other_actor_base_info);
		this.Protocol.SetRequest(C2sProtocol.cs_get_other_actor_base_info, Sproto.cs_get_other_actor_base_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_other_actor_info);
		this.Protocol.SetRequest(C2sProtocol.cs_get_other_actor_info, Sproto.cs_get_other_actor_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_qzonewanba_gift);
		this.Protocol.SetRequest(C2sProtocol.cs_get_qzonewanba_gift, Sproto.cs_get_qzonewanba_gift_request);
		this.Protocol.SetResponse(C2sProtocol.cs_get_qzonewanba_gift, Sproto.cs_get_qzonewanba_gift_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_qzonewanba_vipgift);
		this.Protocol.SetRequest(C2sProtocol.cs_get_qzonewanba_vipgift, Sproto.cs_get_qzonewanba_vipgift_request);
		this.Protocol.SetResponse(C2sProtocol.cs_get_qzonewanba_vipgift, Sproto.cs_get_qzonewanba_vipgift_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_qzonewanba_vipprivilege);
		this.Protocol.SetRequest(C2sProtocol.cs_get_qzonewanba_vipprivilege, Sproto.cs_get_qzonewanba_vipprivilege_request);
		this.Protocol.SetResponse(C2sProtocol.cs_get_qzonewanba_vipprivilege, Sproto.cs_get_qzonewanba_vipprivilege_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_qzonewanba_vipprivilege_stat);
		this.Protocol.SetRequest(C2sProtocol.cs_get_qzonewanba_vipprivilege_stat, Sproto.cs_get_qzonewanba_vipprivilege_stat_request);
		this.Protocol.SetResponse(C2sProtocol.cs_get_qzonewanba_vipprivilege_stat, Sproto.cs_get_qzonewanba_vipprivilege_stat_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_server_time);
		this.Protocol.SetRequest(C2sProtocol.cs_get_server_time, Sproto.cs_get_server_time_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_treasure_boss_list);
		this.Protocol.SetRequest(C2sProtocol.cs_get_treasure_boss_list, Sproto.cs_get_treasure_boss_list_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_treasure_daily_award);
		this.Protocol.SetRequest(C2sProtocol.cs_get_treasure_daily_award, Sproto.cs_get_treasure_daily_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_tryroad_award);
		this.Protocol.SetRequest(C2sProtocol.cs_get_tryroad_award, Sproto.cs_get_tryroad_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_get_tryroad_rank);
		this.Protocol.SetRequest(C2sProtocol.cs_get_tryroad_rank, Sproto.cs_get_tryroad_rank_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gold_guaji_combat_boss);
		this.Protocol.SetRequest(C2sProtocol.cs_gold_guaji_combat_boss, Sproto.cs_gold_guaji_combat_boss_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gold_guaji_info);
		this.Protocol.SetRequest(C2sProtocol.cs_gold_guaji_info, Sproto.cs_gold_guaji_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gold_guaji_obtain_items_info);
		this.Protocol.SetRequest(C2sProtocol.cs_gold_guaji_obtain_items_info, Sproto.cs_gold_guaji_obtain_items_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gold_guaji_start_combat);
		this.Protocol.SetRequest(C2sProtocol.cs_gold_guaji_start_combat, Sproto.cs_gold_guaji_start_combat_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_gold_guaji_start_relive);
		this.Protocol.SetRequest(C2sProtocol.cs_gold_guaji_start_relive, Sproto.cs_gold_guaji_start_relive_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_activity_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_boss_call);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_boss_fight);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_boss_rank);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_change_notice);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_change_notice, Sproto.cs_guild_change_notice_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_change_office);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_change_office, Sproto.cs_guild_change_office_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_contribute);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_contribute, Sproto.cs_guild_contribute_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_create);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_create, Sproto.cs_guild_create_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_demise);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_getallchat);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_getapply);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_getconcount);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_gethistory);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_getinfo);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_getlist);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_getmembers);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_getplayerinfo);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_getskillinfo);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_gettaskaward);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_gettaskaward, Sproto.cs_guild_gettaskaward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_join);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_join, Sproto.cs_guild_join_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_kick);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_kick, Sproto.cs_guild_kick_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_learnskill);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_learnskill, Sproto.cs_guild_learnskill_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_quit);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_raid_attack);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_raid_boost);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_raid_daily);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_raid_daily, Sproto.cs_guild_raid_daily_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_raid_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_raid_reward);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_raid_sweep);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_raid_sweep, Sproto.cs_guild_raid_sweep_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_robber_attack);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_robber_attack, Sproto.cs_guild_robber_attack_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_robber_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_sendchat);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_sendchat, Sproto.cs_guild_sendchat_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_setapply);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_setapply, Sproto.cs_guild_setapply_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_setautoadd);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_setautoadd, Sproto.cs_guild_setautoadd_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_temperskill);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_temperskill, Sproto.cs_guild_temperskill_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guild_upbuilding);
		this.Protocol.SetRequest(C2sProtocol.cs_guild_upbuilding, Sproto.cs_guild_upbuilding_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildshop_getinfo);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildshop_getrecord);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildshop_open);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_disp_award);
		this.Protocol.SetRequest(C2sProtocol.cs_guildwar_disp_award, Sproto.cs_guildwar_disp_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_get_dayaward);
		this.Protocol.SetRequest(C2sProtocol.cs_guildwar_get_dayaward, Sproto.cs_guildwar_get_dayaward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_get_firstwinner_award);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_get_kffz_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_get_kfwin_records);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_get_my_guild_rank_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_get_redpacket);
		this.Protocol.SetRequest(C2sProtocol.cs_guildwar_get_redpacket, Sproto.cs_guildwar_get_redpacket_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_get_winleader);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_get_winnerinfo);
		this.Protocol.SetRequest(C2sProtocol.cs_guildwar_get_winnerinfo, Sproto.cs_guildwar_get_winnerinfo_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_guildwar_send_redpacket);
		this.Protocol.SetRequest(C2sProtocol.cs_guildwar_send_redpacket, Sproto.cs_guildwar_send_redpacket_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_holygun_achievement);
		this.Protocol.SetRequest(C2sProtocol.cs_holygun_achievement, Sproto.cs_holygun_achievement_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_holygun_eatdanyao);
		this.Protocol.SetRequest(C2sProtocol.cs_holygun_eatdanyao, Sproto.cs_holygun_eatdanyao_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_holygun_init);
		this.Protocol.SetRequest(C2sProtocol.cs_holygun_init, Sproto.cs_holygun_init_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_holygun_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_holygun_reward, Sproto.cs_holygun_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_holygun_upscala);
		this.Protocol.SetRequest(C2sProtocol.cs_holygun_upscala, Sproto.cs_holygun_upscala_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_holygun_upskill);
		this.Protocol.SetRequest(C2sProtocol.cs_holygun_upskill, Sproto.cs_holygun_upskill_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_holygun_upstar);
		this.Protocol.SetRequest(C2sProtocol.cs_holygun_upstar, Sproto.cs_holygun_upstar_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_jingmai_boost);
		this.Protocol.SetRequest(C2sProtocol.cs_jingmai_boost, Sproto.cs_jingmai_boost_request);
		this.Protocol.SetResponse(C2sProtocol.cs_jingmai_boost, Sproto.cs_jingmai_boost_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_jingmai_stage);
		this.Protocol.SetRequest(C2sProtocol.cs_jingmai_stage, Sproto.cs_jingmai_stage_request);
		this.Protocol.SetResponse(C2sProtocol.cs_jingmai_stage, Sproto.cs_jingmai_stage_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_jingmai_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_jingmai_upgrade, Sproto.cs_jingmai_upgrade_request);
		this.Protocol.SetResponse(C2sProtocol.cs_jingmai_upgrade, Sproto.cs_jingmai_upgrade_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_ladder_buy_count);

		this.Protocol.SetProtocol(C2sProtocol.cs_ladder_get_rank_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_ladder_get_record);

		this.Protocol.SetProtocol(C2sProtocol.cs_ladder_get_some_one);

		this.Protocol.SetProtocol(C2sProtocol.cs_ladder_get_week_reward);

		this.Protocol.SetProtocol(C2sProtocol.cs_ladder_start_play);
		this.Protocol.SetRequest(C2sProtocol.cs_ladder_start_play, Sproto.cs_ladder_start_play_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_legend_dress);
		this.Protocol.SetRequest(C2sProtocol.cs_legend_dress, Sproto.cs_legend_dress_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_longzhuang_boost);
		this.Protocol.SetRequest(C2sProtocol.cs_longzhuang_boost, Sproto.cs_longzhuang_boost_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_longzhuang_onekey);
		this.Protocol.SetRequest(C2sProtocol.cs_longzhuang_onekey, Sproto.cs_longzhuang_onekey_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_longzhuang_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_longzhuang_upgrade, Sproto.cs_longzhuang_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_luckypackage_testbuy_req);
		this.Protocol.SetRequest(C2sProtocol.cs_luckypackage_testbuy_req, Sproto.cs_luckypackage_testbuy_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_luckywheel_hunt);
		this.Protocol.SetRequest(C2sProtocol.cs_luckywheel_hunt, Sproto.cs_luckywheel_hunt_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_luckywheel_rank);
		this.Protocol.SetRequest(C2sProtocol.cs_luckywheel_rank, Sproto.cs_luckywheel_rank_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_luckywheel_record);
		this.Protocol.SetRequest(C2sProtocol.cs_luckywheel_record, Sproto.cs_luckywheel_record_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mail_delet);
		this.Protocol.SetRequest(C2sProtocol.cs_mail_delet, Sproto.cs_mail_delet_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mail_get_content);
		this.Protocol.SetRequest(C2sProtocol.cs_mail_get_content, Sproto.cs_mail_get_content_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mail_get_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_mail_get_reward, Sproto.cs_mail_get_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mail_init);
		this.Protocol.SetRequest(C2sProtocol.cs_mail_init, Sproto.cs_mail_init_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_miji_fuben);
		this.Protocol.SetRequest(C2sProtocol.cs_miji_fuben, Sproto.cs_miji_fuben_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_miji_fuben_panel_info);
		this.Protocol.SetRequest(C2sProtocol.cs_miji_fuben_panel_info, Sproto.cs_miji_fuben_panel_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_miji_fuben_quick);
		this.Protocol.SetRequest(C2sProtocol.cs_miji_fuben_quick, Sproto.cs_miji_fuben_quick_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_miji_fuben_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_miji_fuben_reward, Sproto.cs_miji_fuben_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_miji_reward_data);
		this.Protocol.SetRequest(C2sProtocol.cs_miji_reward_data, Sproto.cs_miji_reward_data_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mine_mapdata);
		this.Protocol.SetRequest(C2sProtocol.cs_mine_mapdata, Sproto.cs_mine_mapdata_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mine_report_mine_info);
		this.Protocol.SetRequest(C2sProtocol.cs_mine_report_mine_info, Sproto.cs_mine_report_mine_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mine_revenge);
		this.Protocol.SetRequest(C2sProtocol.cs_mine_revenge, Sproto.cs_mine_revenge_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mine_rob);
		this.Protocol.SetRequest(C2sProtocol.cs_mine_rob, Sproto.cs_mine_rob_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mine_steal);
		this.Protocol.SetRequest(C2sProtocol.cs_mine_steal, Sproto.cs_mine_steal_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_mond_Sign_send_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_mond_Sign_send_reward, Sproto.cs_mond_Sign_send_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_money_recharge_get);
		this.Protocol.SetRequest(C2sProtocol.cs_money_recharge_get, Sproto.cs_money_recharge_get_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_money_tree_play);

		this.Protocol.SetProtocol(C2sProtocol.cs_money_tree_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_money_tree_reward, Sproto.cs_money_tree_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_buy_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_buy_req, Sproto.cs_monopoly_buy_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_cheat_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_cheat_req, Sproto.cs_monopoly_cheat_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_dice_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_dice_req, Sproto.cs_monopoly_dice_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_exchange_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_exchange_req, Sproto.cs_monopoly_exchange_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_fire_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_fire_req, Sproto.cs_monopoly_fire_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_raid_open);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_raid_open, Sproto.cs_monopoly_raid_open_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_rank_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_rank_req, Sproto.cs_monopoly_rank_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_req, Sproto.cs_monopoly_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_store_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_store_req, Sproto.cs_monopoly_store_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_tili_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_tili_req, Sproto.cs_monopoly_tili_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_monopoly_use_req);
		this.Protocol.SetRequest(C2sProtocol.cs_monopoly_use_req, Sproto.cs_monopoly_use_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_neigong_info);
		this.Protocol.SetRequest(C2sProtocol.cs_neigong_info, Sproto.cs_neigong_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_neigong_uppro);
		this.Protocol.SetRequest(C2sProtocol.cs_neigong_uppro, Sproto.cs_neigong_uppro_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_neigong_upstar);
		this.Protocol.SetRequest(C2sProtocol.cs_neigong_upstar, Sproto.cs_neigong_upstar_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_offline_apply_req);
		this.Protocol.SetRequest(C2sProtocol.cs_offline_apply_req, Sproto.cs_offline_apply_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_one_gift_buy_test);
		this.Protocol.SetRequest(C2sProtocol.cs_one_gift_buy_test, Sproto.cs_one_gift_buy_test_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_one_gift_rewards);
		this.Protocol.SetRequest(C2sProtocol.cs_one_gift_rewards, Sproto.cs_one_gift_rewards_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_one_recharge_activity_gain);
		this.Protocol.SetRequest(C2sProtocol.cs_one_recharge_activity_gain, Sproto.cs_one_recharge_activity_gain_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_one_recharge_activity_state);
		this.Protocol.SetRequest(C2sProtocol.cs_one_recharge_activity_state, Sproto.cs_one_recharge_activity_state_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_online_req);
		this.Protocol.SetRequest(C2sProtocol.cs_online_req, Sproto.cs_online_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_online_reward_req);
		this.Protocol.SetRequest(C2sProtocol.cs_online_reward_req, Sproto.cs_online_reward_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_operate_share);
		this.Protocol.SetRequest(C2sProtocol.cs_operate_share, Sproto.cs_operate_share_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_paidboss_fight_req);
		this.Protocol.SetRequest(C2sProtocol.cs_paidboss_fight_req, Sproto.cs_paidboss_fight_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_paidboss_req);
		this.Protocol.SetRequest(C2sProtocol.cs_paidboss_req, Sproto.cs_paidboss_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_paidboss_setting_req);
		this.Protocol.SetRequest(C2sProtocol.cs_paidboss_setting_req, Sproto.cs_paidboss_setting_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_activate_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_activate_req, Sproto.cs_pet_activate_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_attach_init_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_attach_init_req, Sproto.cs_pet_attach_init_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_attach_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_attach_req, Sproto.cs_pet_attach_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_attach_unlock_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_attach_unlock_req, Sproto.cs_pet_attach_unlock_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_compose_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_compose_req, Sproto.cs_pet_compose_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_init_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_init_req, Sproto.cs_pet_init_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_pack_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_pack_req, Sproto.cs_pet_pack_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_rename_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_rename_req, Sproto.cs_pet_rename_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_setfight_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_setfight_req, Sproto.cs_pet_setfight_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_skillup_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_skillup_req, Sproto.cs_pet_skillup_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_smelt_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_smelt_req, Sproto.cs_pet_smelt_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_uplevel_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_uplevel_req, Sproto.cs_pet_uplevel_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_upstar_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_upstar_req, Sproto.cs_pet_upstar_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_wake_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_wake_req, Sproto.cs_pet_wake_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_wash_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_wash_req, Sproto.cs_pet_wash_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_washlock_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_washlock_req, Sproto.cs_pet_washlock_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_pet_washrep_req);
		this.Protocol.SetRequest(C2sProtocol.cs_pet_washrep_req, Sproto.cs_pet_washrep_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_petsSearch_hunt);
		this.Protocol.SetRequest(C2sProtocol.cs_petsSearch_hunt, Sproto.cs_petsSearch_hunt_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_prestige_req_topthree);

		this.Protocol.SetProtocol(C2sProtocol.cs_prestige_uplevel);
		this.Protocol.SetRequest(C2sProtocol.cs_prestige_uplevel, Sproto.cs_prestige_uplevel_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_attack_player);
		this.Protocol.SetRequest(C2sProtocol.cs_public_boss_attack_player, Sproto.cs_public_boss_attack_player_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_challenge);
		this.Protocol.SetRequest(C2sProtocol.cs_public_boss_challenge, Sproto.cs_public_boss_challenge_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_challenge_record);
		this.Protocol.SetRequest(C2sProtocol.cs_public_boss_challenge_record, Sproto.cs_public_boss_challenge_record_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_clear_cd);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_rank);
		this.Protocol.SetRequest(C2sProtocol.cs_public_boss_rank, Sproto.cs_public_boss_rank_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_save_autofight);
		this.Protocol.SetRequest(C2sProtocol.cs_public_boss_save_autofight, Sproto.cs_public_boss_save_autofight_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_save_remind);
		this.Protocol.SetRequest(C2sProtocol.cs_public_boss_save_remind, Sproto.cs_public_boss_save_remind_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_send_boos_list);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_send_init_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_boss_send_panel_info);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_challenge_owner);

		this.Protocol.SetProtocol(C2sProtocol.cs_public_relive_cd);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_add_count);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_add_count, Sproto.cs_raid_add_count_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_artifact);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_artifact, Sproto.cs_raid_artifact_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_artifact_award);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_artifact_award, Sproto.cs_raid_artifact_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_artifact_buy_req);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_artifact_buy_req, Sproto.cs_raid_artifact_buy_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_artifact_info);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_artifact_info, Sproto.cs_raid_artifact_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_artifact_morra);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_artifact_morra, Sproto.cs_raid_artifact_morra_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_call_boss_play);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_call_boss_play, Sproto.cs_raid_call_boss_play_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_challenget);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_challenget, Sproto.cs_raid_challenget_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_exit_raid);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_exit_raid, Sproto.cs_raid_exit_raid_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_get_award);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_get_award, Sproto.cs_raid_get_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_get_boss_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_get_boss_reward, Sproto.cs_raid_get_boss_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_get_world_award);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_get_world_award, Sproto.cs_raid_get_world_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_guardian_fight_req);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_guardian_fight_req, Sproto.cs_raid_guardian_fight_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_guardian_quick_req);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_guardian_quick_req, Sproto.cs_raid_guardian_quick_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_guardian_req);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_guardian_req, Sproto.cs_raid_guardian_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_guardian_tili_req);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_guardian_tili_req, Sproto.cs_raid_guardian_tili_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_next_chapter_req);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_next_chapter_req, Sproto.cs_raid_next_chapter_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_pk_boss);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_pk_boss, Sproto.cs_raid_pk_boss_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_raid_wave_complete);
		this.Protocol.SetRequest(C2sProtocol.cs_raid_wave_complete, Sproto.cs_raid_wave_complete_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rank_player_info);
		this.Protocol.SetRequest(C2sProtocol.cs_rank_player_info, Sproto.cs_rank_player_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rank_req);
		this.Protocol.SetRequest(C2sProtocol.cs_rank_req, Sproto.cs_rank_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rank_worship_all_count);
		this.Protocol.SetRequest(C2sProtocol.cs_rank_worship_all_count, Sproto.cs_rank_worship_all_count_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rank_worship_data_req);
		this.Protocol.SetRequest(C2sProtocol.cs_rank_worship_data_req, Sproto.cs_rank_worship_data_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rank_worship_once);
		this.Protocol.SetRequest(C2sProtocol.cs_rank_worship_once, Sproto.cs_rank_worship_once_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rebate_activity_buy);
		this.Protocol.SetRequest(C2sProtocol.cs_rebate_activity_buy, Sproto.cs_rebate_activity_buy_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rebate_activity_gain_other_awards);
		this.Protocol.SetRequest(C2sProtocol.cs_rebate_activity_gain_other_awards, Sproto.cs_rebate_activity_gain_other_awards_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rebate_activity_info);
		this.Protocol.SetRequest(C2sProtocol.cs_rebate_activity_info, Sproto.cs_rebate_activity_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_receive_sorce_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_receive_sorce_reward, Sproto.cs_receive_sorce_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_recharge_get_awards);
		this.Protocol.SetRequest(C2sProtocol.cs_recharge_get_awards, Sproto.cs_recharge_get_awards_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_recharge_gift_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_recharge_gift_reward, Sproto.cs_recharge_gift_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_recharge_month_reward);

		this.Protocol.SetProtocol(C2sProtocol.cs_recharge_test);
		this.Protocol.SetRequest(C2sProtocol.cs_recharge_test, Sproto.cs_recharge_test_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_recharge_test_invest);
		this.Protocol.SetRequest(C2sProtocol.cs_recharge_test_invest, Sproto.cs_recharge_test_invest_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_recharge_test_month);
		this.Protocol.SetRequest(C2sProtocol.cs_recharge_test_month, Sproto.cs_recharge_test_month_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_redeemcode_use);
		this.Protocol.SetRequest(C2sProtocol.cs_redeemcode_use, Sproto.cs_redeemcode_use_request);
		this.Protocol.SetResponse(C2sProtocol.cs_redeemcode_use, Sproto.cs_redeemcode_use_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_revive_actor);
		this.Protocol.SetRequest(C2sProtocol.cs_revive_actor, Sproto.cs_revive_actor_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_change_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_change_req, Sproto.cs_ride_change_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_eat_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_eat_req, Sproto.cs_ride_eat_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_equip_uplevel_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_equip_uplevel_req, Sproto.cs_ride_equip_uplevel_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_equip_upstar_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_equip_upstar_req, Sproto.cs_ride_equip_upstar_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_equipchange_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_equipchange_req, Sproto.cs_ride_equipchange_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_equipoff_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_equipoff_req, Sproto.cs_ride_equipoff_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_getaward_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_getaward_req, Sproto.cs_ride_getaward_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_init_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_init_req, Sproto.cs_ride_init_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_skillup_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_skillup_req, Sproto.cs_ride_skillup_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_uplevel_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_uplevel_req, Sproto.cs_ride_uplevel_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ride_upstar_req);
		this.Protocol.SetRequest(C2sProtocol.cs_ride_upstar_req, Sproto.cs_ride_upstar_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ring_active);
		this.Protocol.SetRequest(C2sProtocol.cs_ring_active, Sproto.cs_ring_active_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ring_soul_evil_change);
		this.Protocol.SetRequest(C2sProtocol.cs_ring_soul_evil_change, Sproto.cs_ring_soul_evil_change_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ring_uplevel);
		this.Protocol.SetRequest(C2sProtocol.cs_ring_uplevel, Sproto.cs_ring_uplevel_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ringboss_init);
		this.Protocol.SetRequest(C2sProtocol.cs_ringboss_init, Sproto.cs_ringboss_init_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rob_biaoche);
		this.Protocol.SetRequest(C2sProtocol.cs_rob_biaoche, Sproto.cs_rob_biaoche_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_rob_biaoche_award);
		this.Protocol.SetRequest(C2sProtocol.cs_rob_biaoche_award, Sproto.cs_rob_biaoche_award_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_send_heart_beat);
		this.Protocol.SetRequest(C2sProtocol.cs_send_heart_beat, Sproto.cs_send_heart_beat_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_sene_gm_command);
		this.Protocol.SetRequest(C2sProtocol.cs_sene_gm_command, Sproto.cs_sene_gm_command_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_set_clientvalue);
		this.Protocol.SetRequest(C2sProtocol.cs_set_clientvalue, Sproto.cs_set_clientvalue_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_set_is_open_payfrist);
		this.Protocol.SetRequest(C2sProtocol.cs_set_is_open_payfrist, Sproto.cs_set_is_open_payfrist_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shapeshift_send_comcard);
		this.Protocol.SetRequest(C2sProtocol.cs_shapeshift_send_comcard, Sproto.cs_shapeshift_send_comcard_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shapeshift_send_info);
		this.Protocol.SetRequest(C2sProtocol.cs_shapeshift_send_info, Sproto.cs_shapeshift_send_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shapeshift_send_join);
		this.Protocol.SetRequest(C2sProtocol.cs_shapeshift_send_join, Sproto.cs_shapeshift_send_join_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shapeshift_send_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_shapeshift_send_upgrade, Sproto.cs_shapeshift_send_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_share_Help);
		this.Protocol.SetRequest(C2sProtocol.cs_share_Help, Sproto.cs_share_Help_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_share_event);
		this.Protocol.SetRequest(C2sProtocol.cs_share_event, Sproto.cs_share_event_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shiliansha_send_buff);
		this.Protocol.SetRequest(C2sProtocol.cs_shiliansha_send_buff, Sproto.cs_shiliansha_send_buff_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shiliansha_send_buy_buff);
		this.Protocol.SetRequest(C2sProtocol.cs_shiliansha_send_buy_buff, Sproto.cs_shiliansha_send_buy_buff_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shiliansha_send_continue);
		this.Protocol.SetRequest(C2sProtocol.cs_shiliansha_send_continue, Sproto.cs_shiliansha_send_continue_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shiliansha_send_enter);
		this.Protocol.SetRequest(C2sProtocol.cs_shiliansha_send_enter, Sproto.cs_shiliansha_send_enter_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shiliansha_send_info);
		this.Protocol.SetRequest(C2sProtocol.cs_shiliansha_send_info, Sproto.cs_shiliansha_send_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_buy);
		this.Protocol.SetRequest(C2sProtocol.cs_shop_buy, Sproto.cs_shop_buy_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_buy_jifen);
		this.Protocol.SetRequest(C2sProtocol.cs_shop_buy_jifen, Sproto.cs_shop_buy_jifen_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_buy_medal);
		this.Protocol.SetRequest(C2sProtocol.cs_shop_buy_medal, Sproto.cs_shop_buy_medal_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_cross_tianti_glory_buy);
		this.Protocol.SetRequest(C2sProtocol.cs_shop_cross_tianti_glory_buy, Sproto.cs_shop_cross_tianti_glory_buy_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_cross_tianti_glory_times);
		this.Protocol.SetRequest(C2sProtocol.cs_shop_cross_tianti_glory_times, Sproto.cs_shop_cross_tianti_glory_times_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_godequip_buy);
		this.Protocol.SetRequest(C2sProtocol.cs_shop_godequip_buy, Sproto.cs_shop_godequip_buy_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_medal_message);
		this.Protocol.SetRequest(C2sProtocol.cs_shop_medal_message, Sproto.cs_shop_medal_message_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_refresh);
		this.Protocol.SetRequest(C2sProtocol.cs_shop_refresh, Sproto.cs_shop_refresh_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_shop_start_refresh);

		this.Protocol.SetProtocol(C2sProtocol.cs_skill_break);
		this.Protocol.SetRequest(C2sProtocol.cs_skill_break, Sproto.cs_skill_break_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_skill_setfight_req);
		this.Protocol.SetRequest(C2sProtocol.cs_skill_setfight_req, Sproto.cs_skill_setfight_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_skill_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_skill_upgrade, Sproto.cs_skill_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_skill_upgrade_all);
		this.Protocol.SetRequest(C2sProtocol.cs_skill_upgrade_all, Sproto.cs_skill_upgrade_all_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_small_routine_gain);
		this.Protocol.SetRequest(C2sProtocol.cs_small_routine_gain, Sproto.cs_small_routine_gain_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_sore_info);
		this.Protocol.SetRequest(C2sProtocol.cs_sore_info, Sproto.cs_sore_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_start_biaoche);
		this.Protocol.SetRequest(C2sProtocol.cs_start_biaoche, Sproto.cs_start_biaoche_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_task_apply_vitality);
		this.Protocol.SetRequest(C2sProtocol.cs_task_apply_vitality, Sproto.cs_task_apply_vitality_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_task_get_achieve);
		this.Protocol.SetRequest(C2sProtocol.cs_task_get_achieve, Sproto.cs_task_get_achieve_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_task_get_task);
		this.Protocol.SetRequest(C2sProtocol.cs_task_get_task, Sproto.cs_task_get_task_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_task_get_vitality_awards);
		this.Protocol.SetRequest(C2sProtocol.cs_task_get_vitality_awards, Sproto.cs_task_get_vitality_awards_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_task_share_open);
		this.Protocol.SetRequest(C2sProtocol.cs_task_share_open, Sproto.cs_task_share_open_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_task_warorder_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_task_warorder_reward, Sproto.cs_task_warorder_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tatoo_equipoff_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tatoo_equipoff_req, Sproto.cs_tatoo_equipoff_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tatoo_equipon_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tatoo_equipon_req, Sproto.cs_tatoo_equipon_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tatoo_init_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tatoo_init_req, Sproto.cs_tatoo_init_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tatoo_strength_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tatoo_strength_req, Sproto.cs_tatoo_strength_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_team_fight_req);
		this.Protocol.SetRequest(C2sProtocol.cs_team_fight_req, Sproto.cs_team_fight_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_team_info_req);
		this.Protocol.SetRequest(C2sProtocol.cs_team_info_req, Sproto.cs_team_info_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_team_join_req);
		this.Protocol.SetRequest(C2sProtocol.cs_team_join_req, Sproto.cs_team_join_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_team_kick_req);
		this.Protocol.SetRequest(C2sProtocol.cs_team_kick_req, Sproto.cs_team_kick_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_team_quit_req);
		this.Protocol.SetRequest(C2sProtocol.cs_team_quit_req, Sproto.cs_team_quit_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_team_req);
		this.Protocol.SetRequest(C2sProtocol.cs_team_req, Sproto.cs_team_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tendraw_send_draw);
		this.Protocol.SetRequest(C2sProtocol.cs_tendraw_send_draw, Sproto.cs_tendraw_send_draw_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tendraw_send_info);
		this.Protocol.SetRequest(C2sProtocol.cs_tendraw_send_info, Sproto.cs_tendraw_send_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ticket_treasure_hunt);
		this.Protocol.SetRequest(C2sProtocol.cs_ticket_treasure_hunt, Sproto.cs_ticket_treasure_hunt_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ticket_treasure_record);
		this.Protocol.SetRequest(C2sProtocol.cs_ticket_treasure_record, Sproto.cs_ticket_treasure_record_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_ticket_treasure_reward);
		this.Protocol.SetRequest(C2sProtocol.cs_ticket_treasure_reward, Sproto.cs_ticket_treasure_reward_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_title_req);

		this.Protocol.SetProtocol(C2sProtocol.cs_title_set);
		this.Protocol.SetRequest(C2sProtocol.cs_title_set, Sproto.cs_title_set_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tower_award_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tower_award_req, Sproto.cs_tower_award_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tower_enter_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tower_enter_req, Sproto.cs_tower_enter_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tower_floor_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tower_floor_req, Sproto.cs_tower_floor_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tower_init_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tower_init_req, Sproto.cs_tower_init_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_tower_sweep_req);
		this.Protocol.SetRequest(C2sProtocol.cs_tower_sweep_req, Sproto.cs_tower_sweep_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_treasure_hunt);
		this.Protocol.SetRequest(C2sProtocol.cs_treasure_hunt, Sproto.cs_treasure_hunt_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_treasure_record);
		this.Protocol.SetRequest(C2sProtocol.cs_treasure_record, Sproto.cs_treasure_record_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_update_qzonewanba_token);
		this.Protocol.SetRequest(C2sProtocol.cs_update_qzonewanba_token, Sproto.cs_update_qzonewanba_token_request);
		this.Protocol.SetResponse(C2sProtocol.cs_update_qzonewanba_token, Sproto.cs_update_qzonewanba_token_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_uplevel_biaoche);
		this.Protocol.SetRequest(C2sProtocol.cs_uplevel_biaoche, Sproto.cs_uplevel_biaoche_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_use_skill);
		this.Protocol.SetRequest(C2sProtocol.cs_use_skill, Sproto.cs_use_skill_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_vip_boss_challenge_time);
		this.Protocol.SetRequest(C2sProtocol.cs_vip_boss_challenge_time, Sproto.cs_vip_boss_challenge_time_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_vip_boss_init_panel_info);
		this.Protocol.SetRequest(C2sProtocol.cs_vip_boss_init_panel_info, Sproto.cs_vip_boss_init_panel_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_vip_boss_refresh_remind);
		this.Protocol.SetRequest(C2sProtocol.cs_vip_boss_refresh_remind, Sproto.cs_vip_boss_refresh_remind_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_vip_boss_remind_panel_info);
		this.Protocol.SetRequest(C2sProtocol.cs_vip_boss_remind_panel_info, Sproto.cs_vip_boss_remind_panel_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_vipshop_info);
		this.Protocol.SetRequest(C2sProtocol.cs_vipshop_info, Sproto.cs_vipshop_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_wanba_redeemcode_use);
		this.Protocol.SetRequest(C2sProtocol.cs_wanba_redeemcode_use, Sproto.cs_wanba_redeemcode_use_request);
		this.Protocol.SetResponse(C2sProtocol.cs_wanba_redeemcode_use, Sproto.cs_wanba_redeemcode_use_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_wanba_share_use);
		this.Protocol.SetRequest(C2sProtocol.cs_wanba_share_use, Sproto.cs_wanba_share_use_request);
		this.Protocol.SetResponse(C2sProtocol.cs_wanba_share_use, Sproto.cs_wanba_share_use_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_wash_soul_evil_type);
		this.Protocol.SetRequest(C2sProtocol.cs_wash_soul_evil_type, Sproto.cs_wash_soul_evil_type_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_wing_activate);
		this.Protocol.SetRequest(C2sProtocol.cs_wing_activate, Sproto.cs_wing_activate_request);
		this.Protocol.SetResponse(C2sProtocol.cs_wing_activate, Sproto.cs_wing_activate_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_wing_boost);
		this.Protocol.SetRequest(C2sProtocol.cs_wing_boost, Sproto.cs_wing_boost_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_wing_equip);
		this.Protocol.SetRequest(C2sProtocol.cs_wing_equip, Sproto.cs_wing_equip_request);
		this.Protocol.SetResponse(C2sProtocol.cs_wing_equip, Sproto.cs_wing_equip_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_wing_evolution);
		this.Protocol.SetRequest(C2sProtocol.cs_wing_evolution, Sproto.cs_wing_evolution_request);
		this.Protocol.SetResponse(C2sProtocol.cs_wing_evolution, Sproto.cs_wing_evolution_response);

		this.Protocol.SetProtocol(C2sProtocol.cs_wing_exten);
		this.Protocol.SetRequest(C2sProtocol.cs_wing_exten, Sproto.cs_wing_exten_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_wing_onekey);
		this.Protocol.SetRequest(C2sProtocol.cs_wing_onekey, Sproto.cs_wing_onekey_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_wing_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_wing_upgrade, Sproto.cs_wing_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_world_boss_buy_cd);

		this.Protocol.SetProtocol(C2sProtocol.cs_world_boss_challenge);

		this.Protocol.SetProtocol(C2sProtocol.cs_world_boss_join_lottery);

		this.Protocol.SetProtocol(C2sProtocol.cs_world_boss_list);

		this.Protocol.SetProtocol(C2sProtocol.cs_yb_roll_start);
		this.Protocol.SetRequest(C2sProtocol.cs_yb_roll_start, Sproto.cs_yb_roll_start_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_yb_turntable_info);
		this.Protocol.SetRequest(C2sProtocol.cs_yb_turntable_info, Sproto.cs_yb_turntable_info_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuanzhi_active);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuanzhi_active, Sproto.cs_zhuanzhi_active_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuanzhi_donate);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuanzhi_donate, Sproto.cs_zhuanzhi_donate_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuanzhi_enter_raid);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuanzhi_enter_raid, Sproto.cs_zhuanzhi_enter_raid_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuanzhi_jingmai_boost);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuanzhi_jingmai_boost, Sproto.cs_zhuanzhi_jingmai_boost_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuanzhi_jingmai_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuanzhi_jingmai_upgrade, Sproto.cs_zhuanzhi_jingmai_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuanzhi_talent_upgrade);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuanzhi_talent_upgrade, Sproto.cs_zhuanzhi_talent_upgrade_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuanzhi_tasklist_req);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuanzhi_tasklist_req, Sproto.cs_zhuanzhi_tasklist_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuzai_fenjie);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuzai_fenjie, Sproto.cs_zhuzai_fenjie_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuzai_grow);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuzai_grow, Sproto.cs_zhuzai_grow_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zhuzai_shengjie);
		this.Protocol.SetRequest(C2sProtocol.cs_zhuzai_shengjie, Sproto.cs_zhuzai_shengjie_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_boss_buy_cd);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_boss_challenge);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_boss_join_lottery);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_boss_list);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_boss_rank);
		this.Protocol.SetRequest(C2sProtocol.cs_zs_boss_rank, Sproto.cs_zs_boss_rank_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_get_exp);
		this.Protocol.SetRequest(C2sProtocol.cs_zs_get_exp, Sproto.cs_zs_get_exp_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_point_clear);
		this.Protocol.SetRequest(C2sProtocol.cs_zs_point_clear, Sproto.cs_zs_point_clear_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_point_req);
		this.Protocol.SetRequest(C2sProtocol.cs_zs_point_req, Sproto.cs_zs_point_req_request);

		this.Protocol.SetProtocol(C2sProtocol.cs_zs_uplevel);
		this.Protocol.SetRequest(C2sProtocol.cs_zs_uplevel, Sproto.cs_zs_uplevel_request);

		this.Protocol.SetProtocol(C2sProtocol.sc_guildwar_get_actor_scores);
		this.Protocol.SetRequest(C2sProtocol.sc_guildwar_get_actor_scores, Sproto.sc_guildwar_get_actor_scores_request);

		this.Protocol.SetProtocol(C2sProtocol.sc_guildwar_get_guild_scores);
		this.Protocol.SetRequest(C2sProtocol.sc_guildwar_get_guild_scores, Sproto.sc_guildwar_get_guild_scores_request);

		this.Protocol.SetProtocol(C2sProtocol.sc_miji_change);
		this.Protocol.SetRequest(C2sProtocol.sc_miji_change, Sproto.sc_miji_change_request);

		this.Protocol.SetProtocol(C2sProtocol.sc_miji_learn);
		this.Protocol.SetRequest(C2sProtocol.sc_miji_learn, Sproto.sc_miji_learn_request);

		this.Protocol.SetProtocol(C2sProtocol.sc_raid_clear_cd);

		this.Protocol.SetProtocol(C2sProtocol.sc_ringboss_enter_req);
		this.Protocol.SetRequest(C2sProtocol.sc_ringboss_enter_req, Sproto.sc_ringboss_enter_req_request);

		this.Protocol.SetProtocol(C2sProtocol.sc_ringboss_refresh_req);
		this.Protocol.SetRequest(C2sProtocol.sc_ringboss_refresh_req, Sproto.sc_ringboss_refresh_req_request);

		this.Protocol.SetProtocol(C2sProtocol.sc_vip_get_awards);
		this.Protocol.SetRequest(C2sProtocol.sc_vip_get_awards, Sproto.sc_vip_get_awards_request);

	}

}