// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_chat_send_info_request extends Sproto.SprotoTypeBase {
		
		public type: number; // tag 0
		public pointId: number; // tag 1
		public str: string; // tag 2
		public bool: boolean; // tag 3
		public constructor(buffer: Uint8Array = null) {
			super(4, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.type = this.de.ri ();
					break;
				case 1:
					this.pointId = this.de.ri ();
					break;
				case 2:
					this.str = this.de.rs ();
					break;
				case 3:
					this.bool = this.de.rb ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.type != undefined) {
				this.se.wi (this.type, 0);
			}

			if (this.pointId != undefined) {
				this.se.wi (this.pointId, 1);
			}

			if (this.str != undefined) {
				this.se.ws (this.str, 2);
			}

			if (this.bool != undefined) {
				this.se.wb (this.bool, 3);
			}

			return this.se.Close ();
		}
	}


}

