// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class sc_dress_time_end_request extends Sproto.SprotoTypeBase {
		
		public dressId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.dressId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.dressId != undefined) {
				this.se.wi (this.dressId, 0);
			}

			return this.se.Close ();
		}
	}


}

