// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class sc_fuwen_equipup_data_request extends Sproto.SprotoTypeBase {
		
		public roleID: number; // tag 0
		public equipPos: number; // tag 1
		public data: item_data; // tag 2
		public level: number; // tag 3
		public constructor(buffer: Uint8Array = null) {
			super(4, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleID = this.de.ri ();
					break;
				case 1:
					this.equipPos = this.de.ri ();
					break;
				case 2:
					this.data = this.de.ro(item_data);
					break;
				case 3:
					this.level = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleID != undefined) {
				this.se.wi (this.roleID, 0);
			}

			if (this.equipPos != undefined) {
				this.se.wi (this.equipPos, 1);
			}

			if (this.data != undefined) {
				this.se.wo (this.data, 2);
			}

			if (this.level != undefined) {
				this.se.wi (this.level, 3);
			}

			return this.se.Close ();
		}
	}


	export class sc_fuwen_open_ret_request extends Sproto.SprotoTypeBase {
		
		public roleID: number; // tag 0
		public result: number; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleID = this.de.ri ();
					break;
				case 1:
					this.result = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleID != undefined) {
				this.se.wi (this.roleID, 0);
			}

			if (this.result != undefined) {
				this.se.wi (this.result, 1);
			}

			return this.se.Close ();
		}
	}


}

