// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_gem_onekey_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_gem_upgrade_grade_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public pos: number; // tag 1
		public canUseYuanbao: boolean; // tag 2
		public constructor(buffer: Uint8Array = null) {
			super(3, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				case 1:
					this.pos = this.de.ri ();
					break;
				case 2:
					this.canUseYuanbao = this.de.rb ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			if (this.pos != undefined) {
				this.se.wi (this.pos, 1);
			}

			if (this.canUseYuanbao != undefined) {
				this.se.wb (this.canUseYuanbao, 2);
			}

			return this.se.Close ();
		}
	}


}

