// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_longzhuang_boost_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public id: number; // tag 1
		public canUseYuanbao: boolean; // tag 2
		public constructor(buffer: Uint8Array = null) {
			super(3, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				case 1:
					this.id = this.de.ri ();
					break;
				case 2:
					this.canUseYuanbao = this.de.rb ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			if (this.id != undefined) {
				this.se.wi (this.id, 1);
			}

			if (this.canUseYuanbao != undefined) {
				this.se.wb (this.canUseYuanbao, 2);
			}

			return this.se.Close ();
		}
	}


	export class cs_longzhuang_onekey_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_longzhuang_upgrade_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public id: number; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				case 1:
					this.id = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			if (this.id != undefined) {
				this.se.wi (this.id, 1);
			}

			return this.se.Close ();
		}
	}


}

