// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_mine_mapdata_request extends Sproto.SprotoTypeBase {
		
		public mapIndex: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.mapIndex = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.mapIndex != undefined) {
				this.se.wi (this.mapIndex, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_mine_report_mine_info_request extends Sproto.SprotoTypeBase {
		
		public type: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.type = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.type != undefined) {
				this.se.wi (this.type, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_mine_revenge_request extends Sproto.SprotoTypeBase {
		
		public acId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.acId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.acId != undefined) {
				this.se.wi (this.acId, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_mine_rob_request extends Sproto.SprotoTypeBase {
		
		public acId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.acId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.acId != undefined) {
				this.se.wi (this.acId, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_mine_steal_request extends Sproto.SprotoTypeBase {
		
		public acId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.acId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.acId != undefined) {
				this.se.wi (this.acId, 0);
			}

			return this.se.Close ();
		}
	}


}

