// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class sc_tatoo_add_res_request extends Sproto.SprotoTypeBase {
		
		public data: tatoo_bag_item; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.data = this.de.ro(tatoo_bag_item);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.data != undefined) {
				this.se.wo (this.data, 0);
			}

			return this.se.Close ();
		}
	}


	export class sc_tatoo_bag_init_request extends Sproto.SprotoTypeBase {
		
		public code: number; // tag 0
		public datas: tatoo_bag_item[]; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.code = this.de.ri ();
					break;
				case 1:
					this.datas = this.de.roa(tatoo_bag_item);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.code != undefined) {
				this.se.wi (this.code, 0);
			}

			if (this.datas != undefined) {
				this.se.woa (this.datas, 1);
			}

			return this.se.Close ();
		}
	}


	export class sc_tatoo_equipoff_res_request extends Sproto.SprotoTypeBase {
		
		public roleid: number; // tag 0
		public slot: number; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleid = this.de.ri ();
					break;
				case 1:
					this.slot = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleid != undefined) {
				this.se.wi (this.roleid, 0);
			}

			if (this.slot != undefined) {
				this.se.wi (this.slot, 1);
			}

			return this.se.Close ();
		}
	}


	export class sc_tatoo_equipon_res_request extends Sproto.SprotoTypeBase {
		
		public roleid: number; // tag 0
		public item: tatoo_item; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleid = this.de.ri ();
					break;
				case 1:
					this.item = this.de.ro(tatoo_item);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleid != undefined) {
				this.se.wi (this.roleid, 0);
			}

			if (this.item != undefined) {
				this.se.wo (this.item, 1);
			}

			return this.se.Close ();
		}
	}


	export class sc_tatoo_init_res_request extends Sproto.SprotoTypeBase {
		
		public data: tatoo_data[]; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.data = this.de.roa(tatoo_data);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.data != undefined) {
				this.se.woa (this.data, 0);
			}

			return this.se.Close ();
		}
	}


	export class sc_tatoo_strength_res_request extends Sproto.SprotoTypeBase {
		
		public roleid: number; // tag 0
		public item: tatoo_item; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleid = this.de.ri ();
					break;
				case 1:
					this.item = this.de.ro(tatoo_item);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleid != undefined) {
				this.se.wi (this.roleid, 0);
			}

			if (this.item != undefined) {
				this.se.wo (this.item, 1);
			}

			return this.se.Close ();
		}
	}


	export class tatoo_bag_item extends Sproto.SprotoTypeBase {
		
		public handle: number; // tag 0
		public configID: number; // tag 1
		public att: attribute_data[]; // tag 2
		public level: number; // tag 3
		public exp: number; // tag 4
		public mainid: number; // tag 5
		public constructor(buffer: Uint8Array = null) {
			super(6, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.handle = this.de.ri ();
					break;
				case 1:
					this.configID = this.de.ri ();
					break;
				case 2:
					this.att = this.de.roa(attribute_data);
					break;
				case 3:
					this.level = this.de.ri ();
					break;
				case 4:
					this.exp = this.de.ri ();
					break;
				case 5:
					this.mainid = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.handle != undefined) {
				this.se.wi (this.handle, 0);
			}

			if (this.configID != undefined) {
				this.se.wi (this.configID, 1);
			}

			if (this.att != undefined) {
				this.se.woa (this.att, 2);
			}

			if (this.level != undefined) {
				this.se.wi (this.level, 3);
			}

			if (this.exp != undefined) {
				this.se.wi (this.exp, 4);
			}

			if (this.mainid != undefined) {
				this.se.wi (this.mainid, 5);
			}

			return this.se.Close ();
		}
	}


	export class tatoo_data extends Sproto.SprotoTypeBase {
		
		public roleid: number; // tag 0
		public tatoo: tatoo_item[]; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleid = this.de.ri ();
					break;
				case 1:
					this.tatoo = this.de.roa(tatoo_item);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleid != undefined) {
				this.se.wi (this.roleid, 0);
			}

			if (this.tatoo != undefined) {
				this.se.woa (this.tatoo, 1);
			}

			return this.se.Close ();
		}
	}


	export class tatoo_item extends Sproto.SprotoTypeBase {
		
		public slot: number; // tag 0
		public itemid: number; // tag 1
		public level: number; // tag 2
		public exp: number; // tag 3
		public attr: attribute_data[]; // tag 4
		public mainid: number; // tag 5
		public constructor(buffer: Uint8Array = null) {
			super(6, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.slot = this.de.ri ();
					break;
				case 1:
					this.itemid = this.de.ri ();
					break;
				case 2:
					this.level = this.de.ri ();
					break;
				case 3:
					this.exp = this.de.ri ();
					break;
				case 4:
					this.attr = this.de.roa(attribute_data);
					break;
				case 5:
					this.mainid = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.slot != undefined) {
				this.se.wi (this.slot, 0);
			}

			if (this.itemid != undefined) {
				this.se.wi (this.itemid, 1);
			}

			if (this.level != undefined) {
				this.se.wi (this.level, 2);
			}

			if (this.exp != undefined) {
				this.se.wi (this.exp, 3);
			}

			if (this.attr != undefined) {
				this.se.woa (this.attr, 4);
			}

			if (this.mainid != undefined) {
				this.se.wi (this.mainid, 5);
			}

			return this.se.Close ();
		}
	}


}

