// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class sc_enter_tryroad_raid_request extends Sproto.SprotoTypeBase {
		
		public status: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.status = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.status != undefined) {
				this.se.wi (this.status, 0);
			}

			return this.se.Close ();
		}
	}


	export class sc_get_caiquan_result_request extends Sproto.SprotoTypeBase {
		
		public result: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.result = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.result != undefined) {
				this.se.wi (this.result, 0);
			}

			return this.se.Close ();
		}
	}


	export class sc_get_tryroad_award_request extends Sproto.SprotoTypeBase {
		
		public id: number; // tag 0
		public status: number; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.id = this.de.ri ();
					break;
				case 1:
					this.status = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.id != undefined) {
				this.se.wi (this.id, 0);
			}

			if (this.status != undefined) {
				this.se.wi (this.status, 1);
			}

			return this.se.Close ();
		}
	}


	export class sc_get_tryroad_rank_request extends Sproto.SprotoTypeBase {
		
		public rank: number; // tag 0
		public lvl: number; // tag 1
		public data: tryroad_rank_data[]; // tag 2
		public constructor(buffer: Uint8Array = null) {
			super(3, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.rank = this.de.ri ();
					break;
				case 1:
					this.lvl = this.de.ri ();
					break;
				case 2:
					this.data = this.de.roa(tryroad_rank_data);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.rank != undefined) {
				this.se.wi (this.rank, 0);
			}

			if (this.lvl != undefined) {
				this.se.wi (this.lvl, 1);
			}

			if (this.data != undefined) {
				this.se.woa (this.data, 2);
			}

			return this.se.Close ();
		}
	}


	export class sc_tryroad_datas_request extends Sproto.SprotoTypeBase {
		
		public id: number; // tag 0
		public status: number; // tag 1
		public rewards: tryroad_reward_data[]; // tag 2
		public constructor(buffer: Uint8Array = null) {
			super(3, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.id = this.de.ri ();
					break;
				case 1:
					this.status = this.de.ri ();
					break;
				case 2:
					this.rewards = this.de.roa(tryroad_reward_data);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.id != undefined) {
				this.se.wi (this.id, 0);
			}

			if (this.status != undefined) {
				this.se.wi (this.status, 1);
			}

			if (this.rewards != undefined) {
				this.se.woa (this.rewards, 2);
			}

			return this.se.Close ();
		}
	}


	export class tryroad_rank_data extends Sproto.SprotoTypeBase {
		
		public rank: number; // tag 0
		public lvl: number; // tag 1
		public name: string; // tag 2
		public vip: number; // tag 3
		public constructor(buffer: Uint8Array = null) {
			super(4, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.rank = this.de.ri ();
					break;
				case 1:
					this.lvl = this.de.ri ();
					break;
				case 2:
					this.name = this.de.rs ();
					break;
				case 3:
					this.vip = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.rank != undefined) {
				this.se.wi (this.rank, 0);
			}

			if (this.lvl != undefined) {
				this.se.wi (this.lvl, 1);
			}

			if (this.name != undefined) {
				this.se.ws (this.name, 2);
			}

			if (this.vip != undefined) {
				this.se.wi (this.vip, 3);
			}

			return this.se.Close ();
		}
	}


	export class tryroad_reward_data extends Sproto.SprotoTypeBase {
		
		public id: number; // tag 0
		public status: number; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.id = this.de.ri ();
					break;
				case 1:
					this.status = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.id != undefined) {
				this.se.wi (this.id, 0);
			}

			if (this.status != undefined) {
				this.se.wi (this.status, 1);
			}

			return this.se.Close ();
		}
	}


}

