// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_wing_activate_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_activate_response extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public openStatus: boolean; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				case 1:
					this.openStatus = this.de.rb ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			if (this.openStatus != undefined) {
				this.se.wb (this.openStatus, 1);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_boost_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public type: number; // tag 1
		public canUseYuanbao: boolean; // tag 2
		public constructor(buffer: Uint8Array = null) {
			super(3, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				case 1:
					this.type = this.de.ri ();
					break;
				case 2:
					this.canUseYuanbao = this.de.rb ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			if (this.type != undefined) {
				this.se.wi (this.type, 1);
			}

			if (this.canUseYuanbao != undefined) {
				this.se.wb (this.canUseYuanbao, 2);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_equip_request extends Sproto.SprotoTypeBase {
		
		public itemHandle: number; // tag 0
		public roleId: number; // tag 1
		public dressIndex: number; // tag 2
		public constructor(buffer: Uint8Array = null) {
			super(3, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.itemHandle = this.de.ri ();
					break;
				case 1:
					this.roleId = this.de.ri ();
					break;
				case 2:
					this.dressIndex = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.itemHandle != undefined) {
				this.se.wi (this.itemHandle, 0);
			}

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 1);
			}

			if (this.dressIndex != undefined) {
				this.se.wi (this.dressIndex, 2);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_equip_response extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public index: number; // tag 1
		public itemData: item_data; // tag 2
		public constructor(buffer: Uint8Array = null) {
			super(3, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				case 1:
					this.index = this.de.ri ();
					break;
				case 2:
					this.itemData = this.de.ro(item_data);
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			if (this.index != undefined) {
				this.se.wi (this.index, 1);
			}

			if (this.itemData != undefined) {
				this.se.wo (this.itemData, 2);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_evolution_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_evolution_response extends Sproto.SprotoTypeBase {
		
		public result: number; // tag 0
		public type: number; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.result = this.de.ri ();
					break;
				case 1:
					this.type = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.result != undefined) {
				this.se.wi (this.result, 0);
			}

			if (this.type != undefined) {
				this.se.wi (this.type, 1);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_exten_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public lv: number; // tag 1
		public constructor(buffer: Uint8Array = null) {
			super(2, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				case 1:
					this.lv = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			if (this.lv != undefined) {
				this.se.wi (this.lv, 1);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_onekey_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			return this.se.Close ();
		}
	}


	export class cs_wing_upgrade_request extends Sproto.SprotoTypeBase {
		
		public roleId: number; // tag 0
		public constructor(buffer: Uint8Array = null) {
			super(1, buffer);
		}

		protected Decode (): void {
			let tag = -1;
			while (-1 != (tag = this.de.rt())) {
				switch (tag) {
				case 0:
					this.roleId = this.de.ri ();
					break;
				default:
					this.de.ReadUnknowData ();
					break;
				}
			}
		}

		public EncodeStream (stream: Sproto.SprotoStream): number {
			this.se.Open (stream);

			if (this.roleId != undefined) {
				this.se.wi (this.roleId, 0);
			}

			return this.se.Close ();
		}
	}


}

