
// //货币名称
// var MoneyConstToName = {
//     [MoneyConst.exp]: window["lanMoney0"],
//     [MoneyConst.gold]: window["lanMoney1"],
//     [MoneyConst.yuanbao]: window["lanMoney2"],
//     [MoneyConst.fame]: window["lanMoney3"],
//     [MoneyConst.soul]: window["lanMoney4"],
//     // [MoneyConst.wing]: "羽毛",
//     [MoneyConst.FEATS]: window["lanMoney7"],
//     [MoneyConst.RedNameScore]: window["lanMoney8"],
//     [MoneyConst.PRESTIGE]: window["lanMoney10"],
//     [MoneyConst.RECHARGE]: window["lanMoney99"],
//     [MoneyConst.PETCREDIT]: window["lanMoney20"],
//     [MoneyConst.RIDECREDIT]: window["lanMoney21"],
//     [MoneyConst.CROSSCREDIT]: window["lanMoney22"],
//     [MoneyConst.GuildContrib]: window["lanMoney5"],
//     [MoneyConst.GuildFund]: window["lanMoney6"],
//     [MoneyConst.ZHENQI]: window["lanMoney14"],
//     [MoneyConst.VIPEXP]: window["lanMoney15"],
//     [MoneyConst.MiJing]: window["lanMoney16"],
//     [MoneyConst.ARTIFACTCREDIT]: window["lanMoney23"],
//     [MoneyConst.sharecoin]: window["lanMoney17"],
//     [MoneyConst.WARORDER]: window["lanMoney24"],
// }
// //货币资源
// var MoneyConstToSource = {
//     [MoneyConst.exp]: "propIcon_026_png",
//     [MoneyConst.gold]: "propIcon_025_png",
//     [MoneyConst.yuanbao]: "propIcon_030_png",
//     [MoneyConst.fame]: "propIcon_029_png",
//     [MoneyConst.soul]: "propIcon_031_png",
//     [MoneyConst.XIUWEI]: "propIcon_033_png",
//     [MoneyConst.FEATS]: "propIcon_028_png",
//     [MoneyConst.RedNameScore]: "",
//     [MoneyConst.PRESTIGE]: "propIcon_027_png",
//     [MoneyConst.RECHARGE]: "propIcon_030_png",
//     [MoneyConst.PETCREDIT]: "290004_png",
//     [MoneyConst.RIDECREDIT]: "290010_png",
//     [MoneyConst.CROSSCREDIT]: "290011_png",
//     [MoneyConst.GuildContrib]: "propIcon_024_png",
//     [MoneyConst.GuildFund]: "propIcon_023_png",
//     [MoneyConst.ZHENQI]: "propIcon_034_png",
//     [MoneyConst.VIPEXP]: "propIcon_032_png",
//     [MoneyConst.MiJing]: "propIcon_148_png",
//     [MoneyConst.ARTIFACTCREDIT]: "290013_png",
//     [MoneyConst.sharecoin]: "comp_16_18_01_png",
//     [MoneyConst.WARORDER]: "propIcon_049_01_png",
// }

// //货币资源
// var MoneyConstToQuality = {
//     [MoneyConst.exp]: 1,
//     [MoneyConst.gold]: 2,
//     [MoneyConst.yuanbao]: 4,
//     [MoneyConst.fame]: 3,
//     [MoneyConst.soul]: 3,
//     [MoneyConst.XIUWEI]: 4,
//     [MoneyConst.FEATS]: 3,
//     [MoneyConst.RedNameScore]: 3,
//     [MoneyConst.PRESTIGE]: 3,
//     [MoneyConst.RECHARGE]: 3,
//     [MoneyConst.PETCREDIT]: 3,
//     [MoneyConst.RIDECREDIT]: 3,
//     [MoneyConst.CROSSCREDIT]: 3,
//     [MoneyConst.GuildContrib]: 3,
//     [MoneyConst.GuildFund]: 3,
//     [MoneyConst.ZHENQI]: 3,
//     [MoneyConst.VIPEXP]: 3,
//     [MoneyConst.MiJing]: 3,
//     [MoneyConst.ARTIFACTCREDIT]: 3,
//     [MoneyConst.sharecoin]: 3,
//     [MoneyConst.WARORDER]: 4,
// }