enum PackageID {
	/** 默认系统 */
    Default = 0,
    /** 关卡系统 */
    Guanqia = 1,
    /** 技能系统 */
    Skill = 2,
    /**背包系统 */
    Bag = 3,
    /**装备系统 */
    Equip = 4,
    /** pk战 */
    Encounter = 5,
    /** 羽翼 */
    Wing = 6,
    /** 强化 */
    strongthen = 7,
    /** 邮件 */
    Mail = 8,
    /** 任务 */
    Task = 9,
    /** boss系统 */
    Boss = 10,
    /** 宝石系统 */
    Gem = 11,
    /** 元神系统 */
    JingMai = 12,
    /** 转生系统 */
    Zs = 13,
    /** 注灵系统 */
    Zhuling = 14,
    /** 突破系统 */
    Tupo = 15,
    /** 商店系统 */
    Shop = 16,
    /** 特戒 */
    Ring = 17,
    /** 排行榜 */
    Ranking = 18,
    /** vip */
    Vip = 19,
    /** 公告 */
    Notice = 20,
    /** 龙魂护盾 */
    LoongSoul = 21,
    /** 寻宝 */
    TreasureHunt = 22,
    /** 历练 */
    Train = 23,
    /** 挑战副本 */
    FbChallenge = 24,
    /** 活动 */
    Activity = 25,
    /** 神器 */
    Artifact = 26,
    /** 充值 */
    Recharge = 27,
    /** 经验炼制 */
    ExpGold = 28,
    /** 礼包 */
    CDKey = 29,
    /** 聊天 */
    Chat = 30,
    /** 主宰装备点 */
    ZhuZaiEquip = 31,
    /** 转生boss */
    ZsBoss = 32,
    /** 平台活动 */
    pfActivity = 33,
    /** 天梯 */
    Ladder = 34,
    /** 魂珠 */
    Miji = 35,
    /** 金币炼制 */
    moneyTree = 36,
    /** 公会 */
    Guild = 37,
    /** 称号 */
    Title = 38,
    /** 公会副本 */
    GuildFB = 39,
    /** 公会强盗 */
    GuildRobber = 41,
    /** 公会商店 */
    GuildStore = 42,
    /** 战灵 */
    WarSpirit = 43,

    Friends = 47,

    NewFunNotice = 58,

    /** 登录 */
    Login = 255,
}